import 'dart:convert';
import 'package:drift/drift.dart';
import 'app_database.dart';

/// All 90 Recomp Recipes directly sourced from Recomp_Manual_v3.html
/// - 20 Breakfast Recipes (3 chapatis base included)
/// - 20 Lunch Recipes (2 chapatis base included — dry pack)
/// - 20 Dinner Recipes (1 cup white rice included)
/// - 30 Snack Recipes (Diet & High-Protein Snacks)
final List<RecipesCompanion> recompRecipesV3 = [
  // ==========================================
  // BREAKFAST (20 Recipes) — Always 3 chapatis base
  // ==========================================
  RecipesCompanion.insert(
    id: 'vengaya_muttai_poriyal',
    name: '1. Vengaya Muttai Poriyal (Onion Egg Scramble + 3 Chapatis)',
    tamilName: const Value('வெங்காய முட்டை பொரியல்'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Mon'),
    calories: 508.0,
    proteinG: 38.0,
    carbsG: 68.0,
    fatG: 15.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis (no oil)',
      '1 onion (finely chopped)',
      '1 green chili',
      'Curry leaves',
      '1 tsp cooking oil',
      'Salt & turmeric to taste',
    ]),
    method: 'Sauté onion 2 min in 1 tsp oil, splutter curry leaves. Crack in 4 eggs, scramble on medium heat 2–3 min. Done in 6 min. Serve with 3 hot chapatis.',
    shelfLifeTip: const Value('Eaten fresh at home (6:30 AM). [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,south-indian'),
  ),
  RecipesCompanion.insert(
    id: 'milagu_omelette',
    name: '2. Milagu Omelette (Cracked-Pepper Flat Omelette + 3 Chapatis)',
    tamilName: const Value('மிளகு ஆம்லெட்'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Tue'),
    calories: 508.0,
    proteinG: 38.0,
    carbsG: 68.0,
    fatG: 15.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis',
      '1/2 tsp crushed black pepper',
      '1 onion',
      '2 tbsp chopped coriander',
      '1 tsp cooking oil',
      'Salt',
    ]),
    method: 'Whisk eggs with crushed black pepper, onion, coriander, and salt. Cook flat 2 min per side in pan. Pair with 3 chapatis.',
    shelfLifeTip: const Value('Fresh breakfast. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,pepper'),
  ),
  RecipesCompanion.insert(
    id: 'thakkali_muttai',
    name: '3. Thakkali Muttai (Tomato Egg Scramble + 3 Chapatis)',
    tamilName: const Value('தக்காளி முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Wed'),
    calories: 508.0,
    proteinG: 38.0,
    carbsG: 69.0,
    fatG: 15.0,
    fiberG: const Value(9.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis',
      '2 tomatoes (chopped)',
      '1/2 tsp turmeric',
      '1/2 tsp chili powder',
      '1 tsp cooking oil',
      'Salt',
    ]),
    method: 'Cook tomatoes with spices to a jam (4 min), scramble eggs through till just set. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Fresh breakfast. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,tomato'),
  ),
  RecipesCompanion.insert(
    id: 'poondu_milagai_muttai',
    name: '4. Poondu Milagai Muttai (Garlic Chili Scramble + 3 Chapatis)',
    tamilName: const Value('பூண்டு மிளகாய் முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Thu'),
    calories: 508.0,
    proteinG: 38.0,
    carbsG: 68.0,
    fatG: 15.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis',
      '5 garlic cloves (minced)',
      '2 green chilies (slit)',
      '1 tsp cooking oil',
      'Salt',
    ]),
    method: 'Sauté garlic golden in oil (don\'t burn), add green chilies and crack in eggs, scramble 2 min. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Fresh breakfast. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,garlic'),
  ),
  RecipesCompanion.insert(
    id: 'anda_bhurji_mumbai',
    name: '5. Anda Bhurji Mumbai-Style (Spiced Scrambled Egg + 3 Chapatis)',
    tamilName: const Value('அண்டா புர்ஜி'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Fri'),
    calories: 536.0,
    proteinG: 40.0,
    carbsG: 70.0,
    fatG: 16.0,
    fiberG: const Value(9.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis',
      '1 onion',
      '1 tomato',
      '1/2 tsp garam masala',
      '1/2 tsp cumin',
      '2 green chilies',
      '1/2 inch ginger',
      '1 tsp cooking oil',
    ]),
    method: 'Sauté cumin, onion, and ginger. Add tomato, cook down, scramble eggs with garam masala. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Fresh breakfast. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,north-indian'),
  ),
  RecipesCompanion.insert(
    id: 'air_fryer_tandoori_egg',
    name: '6. Air-Fryer Tandoori Egg (Tandoori Eggs + 3 Chapatis)',
    tamilName: const Value('தந்தூரி முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Sat'),
    calories: 544.0,
    proteinG: 40.0,
    carbsG: 70.0,
    fatG: 17.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '4 eggs (boiled 7 min, peeled)',
      '3 whole wheat chapatis',
      '1 tbsp hung curd',
      '1 tsp tandoori masala (MDH/Everest)',
      '1 tsp Kashmiri chili powder',
      '1/2 tsp oil',
    ]),
    method: 'Score eggs with a knife, coat in curd + tandoori masala, air-fry 200°C for 6 min. Smoky char outside, jammy inside. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Air-fryer quick method. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,air-fryer,tandoori,eggs'),
  ),
  RecipesCompanion.insert(
    id: 'egg_keema_breakfast',
    name: '7. Egg Keema Minced Curry (Crumbled Egg + 3 Chapatis)',
    tamilName: const Value('முட்டை கீமா'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Sun'),
    calories: 520.0,
    proteinG: 39.0,
    carbsG: 70.0,
    fatG: 15.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '4 eggs (boiled, roughly crumbled)',
      '3 whole wheat chapatis',
      '1 onion',
      '1 tomato',
      '1/2 tsp garam masala',
      '1/2 tsp chili powder',
      '1 tsp cooking oil',
    ]),
    method: 'Build onion-tomato masala, add crumbled boiled eggs, toss and cook 3 min until coated. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Street style. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,keema'),
  ),
  RecipesCompanion.insert(
    id: 'masala_oats_boiled_egg',
    name: '8. Masala Oats + Boiled Egg (Savory Oats Staple)',
    tamilName: const Value('மசாலா ஓட்ஸ் + முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 492.0,
    proteinG: 36.0,
    carbsG: 78.0,
    fatG: 14.0,
    fiberG: const Value(13.0),
    ingredientsJson: jsonEncode([
      '40g rolled oats',
      '250 ml water',
      '1 onion',
      '1 tomato',
      '1/2 tsp cumin & turmeric',
      '2 whole boiled eggs',
    ]),
    method: 'Boil water, add oats, onion, tomato, and spices. Stir 5 min to thick porridge. Serve with 2 boiled eggs on the side.',
    shelfLifeTip: const Value('Weekday staple. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,oats,eggs'),
  ),
  RecipesCompanion.insert(
    id: 'overnight_oats_whey',
    name: '9. Overnight Oats + Whey (Zero Morning Effort)',
    tamilName: const Value('ஓவர்நைட் ஓட்ஸ் + வே'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 476.0,
    proteinG: 33.0,
    carbsG: 78.0,
    fatG: 14.0,
    fiberG: const Value(14.0),
    ingredientsJson: jsonEncode([
      '40g rolled oats',
      '200 ml whole milk',
      '1/2 scoop whey protein (15g)',
      '1 mashed banana (120g)',
    ]),
    method: 'Mix oats, milk, whey, and mashed banana in a jar the night before. Refrigerate overnight. Eat cold straight from jar.',
    shelfLifeTip: const Value('Zero morning prep. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,oats,whey,no-cook'),
  ),
  RecipesCompanion.insert(
    id: 'oats_upma_egg',
    name: '10. Oats Upma + Egg (South Indian Style Oats)',
    tamilName: const Value('ஓட்ஸ் உப்புமா + முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 494.0,
    proteinG: 36.0,
    carbsG: 84.0,
    fatG: 12.0,
    fiberG: const Value(12.0),
    ingredientsJson: jsonEncode([
      '50g rolled oats',
      'Mustard seeds & curry leaves',
      '1 onion',
      '1 grated carrot',
      '2 scrambled eggs',
      '1 tsp cooking oil',
    ]),
    method: 'Temper mustard and curry leaves, sauté onion and carrot. Add oats + water (1:2), stir to upma, fold in scrambled eggs.',
    shelfLifeTip: const Value('Warm breakfast. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,oats,upma,eggs'),
  ),
  RecipesCompanion.insert(
    id: 'egg_fried_rice_style_breakfast',
    name: '11. Egg Fried Rice Style (Soy Scramble + 3 Chapatis)',
    tamilName: const Value('சோயா சாஸ் முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 524.0,
    proteinG: 39.0,
    carbsG: 72.0,
    fatG: 16.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis',
      '1 tbsp soy sauce',
      '1/2 tsp black pepper',
      '1 tsp cooking oil',
      'Spring onion',
    ]),
    method: 'Beat eggs with soy sauce and pepper. Scramble in hot pan with 1 tsp oil. Top with chopped spring onion. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Fastest 3-ingredient option. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,quick,eggs'),
  ),
  RecipesCompanion.insert(
    id: 'harissa_spicy_egg',
    name: '12. Harissa-Style Spicy Egg (Hot Sauce Scramble + 3 Chapatis)',
    tamilName: const Value('கார முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 508.0,
    proteinG: 38.0,
    carbsG: 68.0,
    fatG: 15.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis',
      '1 tsp hot chilli sauce (Maggi/Sunrise)',
      '1/2 tsp cumin',
      '1 tsp cooking oil',
    ]),
    method: 'Scramble eggs in oil with cumin, stir in hot chilli sauce at the end. Done in 5 min. Serve with 3 chapatis.',
    shelfLifeTip: const Value('2-ingredient side. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,spicy'),
  ),
  RecipesCompanion.insert(
    id: 'italian_herb_omelette',
    name: '13. Italian Herb Omelette (Oregano & Chili + 3 Chapatis)',
    tamilName: const Value('இத்தாலியன் ஹெர்ப் ஆம்லெட்'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 520.0,
    proteinG: 38.0,
    carbsG: 70.0,
    fatG: 15.0,
    fiberG: const Value(9.0),
    ingredientsJson: jsonEncode([
      '4 whole eggs',
      '3 whole wheat chapatis',
      '1/2 tsp oregano (Keya/Catch)',
      '1/2 tsp chili flakes',
      '1 small onion',
      '1 tsp cooking oil',
    ]),
    method: 'Whisk eggs with herbs, chili flakes, and onion. Cook as flat omelette in pan. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Italian seasoning. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,eggs,italian'),
  ),
  RecipesCompanion.insert(
    id: 'paneer_bhurji_light',
    name: '14. Paneer Bhurji Light (Paneer + 2 Eggs + 3 Chapatis)',
    tamilName: const Value('பன்னீர் புர்ஜி'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 535.0,
    proteinG: 41.0,
    carbsG: 72.0,
    fatG: 16.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '60g paneer (crumbled)',
      '2 whole eggs',
      '3 whole wheat chapatis',
      '1 onion',
      '1 tomato',
      '1/2 tsp cumin',
      '1 tsp cooking oil',
    ]),
    method: 'Temper cumin, sauté onion and tomato. Add crumbled paneer and 2 eggs, stir-scramble 3 min. Serve with 3 chapatis.',
    shelfLifeTip: const Value('High protein blend. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,paneer,eggs'),
  ),
  RecipesCompanion.insert(
    id: 'soya_muttai_poriyal',
    name: '15. Soya Muttai Poriyal (Soya Chunks + Egg + 3 Chapatis)',
    tamilName: const Value('சோயா முட்டை பொரியல்'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 496.0,
    proteinG: 37.0,
    carbsG: 75.0,
    fatG: 16.0,
    fiberG: const Value(9.0),
    ingredientsJson: jsonEncode([
      '3 whole eggs',
      '30g dry soya chunks (rehydrated, squeezed)',
      '3 whole wheat chapatis',
      '1 onion',
      '1 tsp cooking oil',
      'Spices to taste',
    ]),
    method: 'Rehydrate soya in hot water 10 min, squeeze dry. Sauté with onion and spices, fold in 3 eggs and scramble. Serve with 3 chapatis.',
    shelfLifeTip: const Value('Highest protein breakfast. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,high-protein,soya,eggs'),
  ),
  RecipesCompanion.insert(
    id: 'banana_oat_egg_pancakes',
    name: '16. Banana Oat Egg Pancakes (3-Ingredient Flourless Pancakes)',
    tamilName: const Value('வாழைப்பழ ஓட்ஸ் பான்கேக்'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekend'),
    calories: 517.0,
    proteinG: 37.0,
    carbsG: 78.0,
    fatG: 16.0,
    fiberG: const Value(13.0),
    ingredientsJson: jsonEncode([
      '2 whole eggs',
      '1 banana (120g)',
      '30g rolled oats',
      'Pinch of cinnamon',
      '1/2 tsp cooking oil',
    ]),
    method: 'Mash banana, mix with oats, eggs, and cinnamon to make batter. Cook small pancakes on pan 2 min per side. Eat instead of chapati.',
    shelfLifeTip: const Value('No flour needed. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,pancakes,banana,oats'),
  ),
  RecipesCompanion.insert(
    id: 'oats_porridge_boiled_eggs',
    name: '17. Oats Porridge + Boiled Eggs (Simplest 5-Min Breakfast)',
    tamilName: const Value('ஓட்ஸ் கஞ்சி + அவித்த முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekday'),
    calories: 490.0,
    proteinG: 33.0,
    carbsG: 77.0,
    fatG: 14.0,
    fiberG: const Value(13.0),
    ingredientsJson: jsonEncode([
      '50g rolled oats',
      '300 ml water',
      'Pinch of salt',
      '3 boiled eggs (pre-boiled)',
    ]),
    method: 'Boil oats in water for 4 min with salt. Serve hot with 3 boiled eggs (boiled the night before).',
    shelfLifeTip: const Value('Fastest possible. [S] Simple Weekday'),
    tags: const Value('breakfast,simple,quick,oats,eggs'),
  ),
  RecipesCompanion.insert(
    id: 'moong_dal_cheela_egg',
    name: '18. Moong Dal Cheela + Egg (High-Protein Lentil Crepe)',
    tamilName: const Value('பாசிப்பருப்பு சீலா + முட்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Sat'),
    calories: 530.0,
    proteinG: 43.0,
    carbsG: 72.0,
    fatG: 17.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '60g split moong (soaked overnight, blended)',
      '2 whole eggs (whisked in)',
      '1 onion & green chili',
      '1/2 tsp oil',
    ]),
    method: 'Blend soaked moong dal to smooth batter. Add eggs, onion, and chili. Pour thin crepe on hot greased pan, cook 2 min/side.',
    shelfLifeTip: const Value('Soak dal overnight. [C] Complex / Weekend'),
    tags: const Value('breakfast,complex,cheela,lentils,weekend'),
  ),
  RecipesCompanion.insert(
    id: 'muttai_kola_urundai_breakfast',
    name: '19. Muttai Kola Urundai (Air-Fryer Spiced Egg Patties)',
    tamilName: const Value('முட்டை கோலா உருண்டை'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Sun'),
    calories: 544.0,
    proteinG: 42.0,
    carbsG: 76.0,
    fatG: 17.0,
    fiberG: const Value(9.0),
    ingredientsJson: jsonEncode([
      '4 whole boiled eggs (mashed)',
      '2 tbsp besan (gram flour)',
      '1 onion',
      '1/2 tsp fennel & spices',
      '1 tsp oil',
    ]),
    method: 'Mix mashed eggs with besan, onion, fennel, and spices into firm dough. Shape into patties, air-fry 190°C for 12 min until golden.',
    shelfLifeTip: const Value('Best with mint chutney. [C] Complex / Weekend'),
    tags: const Value('breakfast,complex,air-fryer,eggs,weekend'),
  ),
  RecipesCompanion.insert(
    id: 'egg_sprouted_moong_bowl',
    name: '20. Egg + Sprouted Moong Bowl (High-Fiber Scramble Bowl)',
    tamilName: const Value('முட்டை முளைகட்டிய பாசிப்பயறு பவுல்'),
    mealSlot: 'breakfast',
    dayOfWeek: const Value('Weekend'),
    calories: 508.0,
    proteinG: 39.0,
    carbsG: 72.0,
    fatG: 17.0,
    fiberG: const Value(10.0),
    ingredientsJson: jsonEncode([
      '3 whole scrambled eggs',
      '60g sprouted green moong',
      '3 whole wheat chapatis',
      'Fresh lemon juice',
      'Chaat masala',
    ]),
    method: 'Scramble eggs with salt and pepper. Toss sprouted moong with lemon juice and chaat masala. Serve together with 3 chapatis.',
    shelfLifeTip: const Value('Sprout 36 hrs ahead. [C] Complex / Weekend'),
    tags: const Value('breakfast,complex,sprouts,eggs,fiber'),
  ),

  // ==========================================
  // LUNCH (20 Recipes) — Always 2 chapatis base (Dry Pack)
  // ==========================================
  RecipesCompanion.insert(
    id: 'air_fryer_tandoori_chicken_lunch',
    name: '1. Air-Fryer Tandoori Chicken (Lunch Box + 2 Chapatis)',
    tamilName: const Value('தந்தூரி சிக்கன் (லஞ்ச்)'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Mon'),
    calories: 445.0,
    proteinG: 42.0,
    carbsG: 44.0,
    fatG: 9.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g boiler chicken breast (cubed)',
      '2 whole wheat chapatis',
      '3 tbsp hung curd',
      '1 tbsp tandoori masala (MDH/Everest)',
      '1 tsp Kashmiri chili powder',
      'Lemon juice & ginger-garlic paste',
    ]),
    method: 'Marinate chicken 30 min or overnight. Air-fry 200°C for 15 min, flip halfway. Char edges = authentic. Cool completely before packing with 2 chapatis.',
    shelfLifeTip: const Value('Cool completely before packing — dry preparation safe 6+ hrs unrefrigerated. [S]'),
    tags: const Value('lunch,simple,dry-pack,air-fryer,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'milagu_kozhi_varuval_lunch',
    name: '2. Milagu Kozhi Varuval (Pepper Chicken Dry Roast + 2 Chapatis)',
    tamilName: const Value('மிளகு கோழி வறுவல்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Tue'),
    calories: 440.0,
    proteinG: 41.0,
    carbsG: 44.0,
    fatG: 9.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g boiler chicken breast',
      '2 whole wheat chapatis',
      '1.5 tsp black pepper',
      '1 tsp ginger-garlic paste',
      'Curry leaves',
      '1 tsp cooking oil',
    ]),
    method: 'Marinate chicken 15 min. Air-fry 200°C for 14 min or pan-roast completely dry with curry leaves and pepper. Cool before packing with 2 chapatis.',
    shelfLifeTip: const Value('4 ingredients. Natural pepper preservative. [S]'),
    tags: const Value('lunch,simple,dry-pack,pepper,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'hariyali_chicken',
    name: '3. Hariyali Chicken Green Masala (Mint Coriander + 2 Chapatis)',
    tamilName: const Value('ஹரியாலி சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Wed'),
    calories: 442.0,
    proteinG: 42.0,
    carbsG: 44.0,
    fatG: 9.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      'Handful mint + coriander (blended to paste)',
      '1 tsp ginger-garlic',
      'Lemon juice',
      '1 tsp oil',
    ]),
    method: 'Coat chicken in green paste, air-fry 200°C for 14 min. Turns beautifully fragrant. Cool and pack with 2 chapatis.',
    shelfLifeTip: const Value('Bright and simple 4-ingredient marinade. [S]'),
    tags: const Value('lunch,simple,dry-pack,hariyali,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'soy_garlic_chicken',
    name: '4. Soy-Garlic Chicken (3-Ingredient Dry Chicken + 2 Chapatis)',
    tamilName: const Value('சோயா கார்லிக் சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Thu'),
    calories: 448.0,
    proteinG: 42.0,
    carbsG: 45.0,
    fatG: 10.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      '2 tbsp soy sauce (DMart)',
      '5 garlic cloves (minced)',
      '1/2 tsp black pepper',
      '1 tsp oil',
    ]),
    method: 'Marinate 20 min in soy sauce, garlic, and pepper. Air-fry 200°C for 14 min. Cool and pack with 2 chapatis.',
    shelfLifeTip: const Value('Global, extremely simple. [S]'),
    tags: const Value('lunch,simple,dry-pack,soy-sauce,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'chilli_garlic_chicken',
    name: '5. Chilli Garlic Chicken Indo-Chinese (Dry Stir-Fry + 2 Chapatis)',
    tamilName: const Value('சில்லி கார்லிக் சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Fri'),
    calories: 444.0,
    proteinG: 42.0,
    carbsG: 44.0,
    fatG: 10.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      '1 tbsp soy sauce',
      '1 tsp chilli sauce (DMart)',
      'Garlic & ginger',
      '50g capsicum',
      '1 tsp oil',
    ]),
    method: 'Stir-fry on highest heat 8 min till absolutely dry. No sauce pooling — it all absorbs. Cool and pack with 2 chapatis.',
    shelfLifeTip: const Value('Indo-Chinese dry style. [S]'),
    tags: const Value('lunch,simple,dry-pack,indo-chinese,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'lemon_pepper_chicken',
    name: '6. Lemon Pepper Chicken (2-Ingredient Prep + 2 Chapatis)',
    tamilName: const Value('லெமன் பெப்பர் சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Sat'),
    calories: 440.0,
    proteinG: 42.0,
    carbsG: 44.0,
    fatG: 9.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      'Juice of 1 lemon',
      '1 tsp black pepper',
      'Pinch of salt',
      '1/2 tsp oil',
    ]),
    method: 'Marinate 15 min in lemon and pepper. Air-fry 200°C for 13 min. Simplest possible chicken prep. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Simplest possible chicken prep. [S]'),
    tags: const Value('lunch,simple,dry-pack,quick,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_tikka_dry',
    name: '7. Chicken Tikka Dry (Air-Fried Cubes + 2 Chapatis)',
    tamilName: const Value('சிக்கன் டிக்கா டிரை'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Sun'),
    calories: 450.0,
    proteinG: 43.0,
    carbsG: 45.0,
    fatG: 10.0,
    fiberG: const Value(7.0),
    ingredientsJson: jsonEncode([
      '180g chicken (cubed)',
      '2 whole wheat chapatis',
      '2 tbsp curd (marinade cooked dry)',
      'Tikka masala (MDH/DMart)',
      'Ginger-garlic',
      '1 tsp oil',
    ]),
    method: 'Marinate cubed chicken in thick tikka masala 30 min. Air-fry 200°C for 12 min. Tikka masala bakes completely dry. Safe to carry with 2 chapatis.',
    shelfLifeTip: const Value('Curd cooks off dry — completely safe. [S]'),
    tags: const Value('lunch,simple,dry-pack,tikka,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'sesame_soy_chicken',
    name: '8. Sesame Soy Chicken (Crunchy Ellu Crust + 2 Chapatis)',
    tamilName: const Value('எள்ளு சோயா சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 455.0,
    proteinG: 43.0,
    carbsG: 47.0,
    fatG: 10.0,
    fiberG: const Value(7.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      '1 tbsp sesame seeds (ellu)',
      '1 tbsp soy sauce',
      '1/2 tsp pepper & ginger',
      '1 tsp oil',
    ]),
    method: 'Coat chicken in sesame + soy + pepper. Air-fry 200°C for 14 min. Sesame crust forms nicely. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Crunchy crust. [S]'),
    tags: const Value('lunch,simple,dry-pack,sesame,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'vella_kadalai_sundal_lunch',
    name: '9. Vella Kadalai Sundal (White Chickpea Box + 2 Chapatis)',
    tamilName: const Value('வெள்ளை கடலை சுண்டல்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 398.0,
    proteinG: 26.0,
    carbsG: 61.0,
    fatG: 9.0,
    fiberG: const Value(15.0),
    ingredientsJson: jsonEncode([
      '80g dry white chickpeas (boiled)',
      '2 whole wheat chapatis',
      'Mustard & curry leaves',
      '2 tbsp grated coconut',
      '1 tsp cooking oil',
      'Salt',
    ]),
    method: 'Temper mustard + curry leaves, add boiled chickpeas + coconut, cook off all moisture 3 min. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Batch cook on Sunday — zero morning prep. [S]'),
    tags: const Value('lunch,simple,dry-pack,sundal,veg'),
  ),
  RecipesCompanion.insert(
    id: 'soya_milagu_varuval_lunch',
    name: '10. Soya Milagu Varuval (Pepper Soya Dry Fry + 2 Chapatis)',
    tamilName: const Value('சோயா மிளகு வறுவல்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 380.0,
    proteinG: 34.0,
    carbsG: 52.0,
    fatG: 8.0,
    fiberG: const Value(11.0),
    ingredientsJson: jsonEncode([
      '50g dry soya chunks (squeezed very dry)',
      '2 whole wheat chapatis',
      '1 onion',
      '1 tsp black pepper',
      'Curry leaves',
      '1 tsp cooking oil',
    ]),
    method: 'Rehydrate in hot water 10 min, squeeze hard. Stir-fry with onion + pepper 8 min till edges crisp. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Squeeze water thoroughly. [S]'),
    tags: const Value('lunch,simple,dry-pack,soya,high-protein'),
  ),
  RecipesCompanion.insert(
    id: 'paneer_tikka_dry',
    name: '11. Paneer Tikka Air-Fried Dry (Cubed Paneer + 2 Chapatis)',
    tamilName: const Value('பன்னீர் டிக்கா (டிரை)'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 442.0,
    proteinG: 30.0,
    carbsG: 52.0,
    fatG: 22.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '100g paneer (cubed)',
      '2 whole wheat chapatis',
      '1 tsp tikka masala (DMart)',
      '1/2 tsp Kashmiri chili',
      'Lemon juice & salt',
      '1/2 tsp oil',
    ]),
    method: 'Coat cubed paneer in spices, air-fry 200°C for 8 min. No marinade required — just toss and fry. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Quick dry paneer. [S]'),
    tags: const Value('lunch,simple,dry-pack,paneer'),
  ),
  RecipesCompanion.insert(
    id: 'soya_chilli_dry',
    name: '12. Soya Chilli Dry (Indo-Chinese Soya + 2 Chapatis)',
    tamilName: const Value('சோயா சில்லி டிரை'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 388.0,
    proteinG: 33.0,
    carbsG: 56.0,
    fatG: 8.0,
    fiberG: const Value(9.0),
    ingredientsJson: jsonEncode([
      '50g dry soya chunks',
      '2 whole wheat chapatis',
      '1 capsicum',
      '1 tbsp soy sauce',
      '1 tsp chilli sauce (DMart)',
      'Garlic',
      '1 tsp oil',
    ]),
    method: 'Rehydrate soya, squeeze dry, stir-fry on high heat with capsicum + sauces till all liquid is absorbed. Pack with 2 chapatis.',
    shelfLifeTip: const Value('All sauce absorbed. [S]'),
    tags: const Value('lunch,simple,dry-pack,soya,indo-chinese'),
  ),
  RecipesCompanion.insert(
    id: 'rajma_poriyal',
    name: '13. Rajma Poriyal (Dry Kidney Bean Stir-Fry + 2 Chapatis)',
    tamilName: const Value('ராஜ்மா பொரியல்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 410.0,
    proteinG: 29.0,
    carbsG: 55.0,
    fatG: 9.0,
    fiberG: const Value(13.0),
    ingredientsJson: jsonEncode([
      '80g dry rajma (soaked & pressure-cooked)',
      '2 whole wheat chapatis',
      'Mustard & curry leaves tempering',
      '1 tsp oil',
      'Salt',
    ]),
    method: 'Cook beans, dry-roast with tempering. Batch cook on Sunday — zero morning prep. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Sunday batch prep. [S]'),
    tags: const Value('lunch,simple,dry-pack,rajma,legumes'),
  ),
  RecipesCompanion.insert(
    id: 'muttai_kola_urundai_packed',
    name: '14. Muttai Kola Urundai Packed (Air-Fried Patties + 2 Chapatis)',
    tamilName: const Value('முட்டை கோலா உருண்டை (பாக்ஸ்)'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 445.0,
    proteinG: 40.0,
    carbsG: 45.0,
    fatG: 11.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '4 boiled eggs (mashed)',
      '2 whole wheat chapatis',
      '2 tbsp besan',
      'Spices & onion',
      '1/2 tsp oil',
    ]),
    method: 'Mix into dough, shape into round patties, air-fry 190°C for 12 min. Very dry — holds shape in box all day. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Travels perfectly in bag. [S]'),
    tags: const Value('lunch,simple,dry-pack,eggs,air-fryer'),
  ),
  RecipesCompanion.insert(
    id: 'ketchup_masala_egg',
    name: '15. Ketchup Masala Egg (4-Ingredient Glaze + 2 Chapatis)',
    tamilName: const Value('கெட்சப் மசாலா முட்டை'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 430.0,
    proteinG: 38.0,
    carbsG: 44.0,
    fatG: 10.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '4 boiled eggs (halved)',
      '2 whole wheat chapatis',
      '2 tbsp tomato ketchup (DMart)',
      '1/2 tsp chili powder',
      '1/2 tsp cumin',
      '1/2 tsp oil',
    ]),
    method: 'Fry halved eggs cut-side down 2 min, pour ketchup + spices, toss to coat, cook 2 min more till dry. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Quick 4-ingredient prep. [S]'),
    tags: const Value('lunch,simple,dry-pack,eggs,quick'),
  ),
  RecipesCompanion.insert(
    id: 'kadai_chicken_chukka',
    name: '16. Kadai Chicken Chukka (Capsicum & Chicken + 2 Chapatis)',
    tamilName: const Value('கடாய் சிக்கன் சுக்கா'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 440.0,
    proteinG: 41.0,
    carbsG: 46.0,
    fatG: 10.0,
    fiberG: const Value(7.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      '1 capsicum',
      '1 onion',
      'Kadai masala / cumin & coriander',
      '1 tsp oil',
    ]),
    method: 'Dry stir-fry chicken and capsicum together on high heat. No water added. Cook off all moisture. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Aromatic dry chukka. [S]'),
    tags: const Value('lunch,simple,dry-pack,kadai,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'mixed_bean_sundal',
    name: '17. Mixed Bean Sundal (Chickpeas & Rajma + 2 Chapatis)',
    tamilName: const Value('மிக்ஸ்ட் பீன்ஸ் சுண்டல்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 420.0,
    proteinG: 33.0,
    carbsG: 56.0,
    fatG: 9.0,
    fiberG: const Value(14.0),
    ingredientsJson: jsonEncode([
      '40g chickpeas + 40g rajma (cooked)',
      '2 whole wheat chapatis',
      'Tempering spices',
      '2 tbsp grated coconut',
      '1 tsp oil',
    ]),
    method: 'Same sundal method. Mix beans for variety and fiber. Pre-cook on Sunday. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Sunday batch prep. [S]'),
    tags: const Value('lunch,simple,dry-pack,sundal,beans'),
  ),
  RecipesCompanion.insert(
    id: 'vinegar_pepper_chicken',
    name: '18. Vinegar-Pepper Chicken (Goan-Style Dry Chicken + 2 Chapatis)',
    tamilName: const Value('வினிகர் பெப்பர் சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 444.0,
    proteinG: 43.0,
    carbsG: 45.0,
    fatG: 9.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      '2 tsp vinegar (DMart)',
      '1 tsp black pepper',
      '4 garlic cloves',
      '1 tsp oil',
    ]),
    method: 'Marinate in vinegar + pepper + garlic 20 min. Pan-roast or air-fry completely dry. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Vinegar natural preservative. [S]'),
    tags: const Value('lunch,simple,dry-pack,vinegar,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'peanut_pepper_chicken',
    name: '19. Peanut Pepper Chicken (Crushed Peanut Crust + 2 Chapatis)',
    tamilName: const Value('வேர்க்கடலை மிளகு சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 450.0,
    proteinG: 43.0,
    carbsG: 46.0,
    fatG: 10.0,
    fiberG: const Value(7.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      '20g peanuts (coarsely crushed)',
      '1 tsp black pepper',
      'Lemon juice',
      '1 tsp oil',
    ]),
    method: 'Coat chicken in peanut + pepper + lemon, air-fry 200°C for 14 min. Crunchy coating. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Nutty crunchy crust. [S]'),
    tags: const Value('lunch,simple,dry-pack,peanut,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'turmeric_lemon_herb_chicken',
    name: '20. Turmeric Lemon Herb Chicken (Mediterranean + 2 Chapatis)',
    tamilName: const Value('மஞ்சள் எலுமிச்சை சிக்கன்'),
    mealSlot: 'lunch',
    dayOfWeek: const Value('Weekday'),
    calories: 438.0,
    proteinG: 42.0,
    carbsG: 44.0,
    fatG: 9.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '180g chicken breast',
      '2 whole wheat chapatis',
      'Juice of 1 lemon',
      '1 tsp turmeric',
      '1/2 tsp oregano (DMart)',
      'Garlic',
      '1 tsp oil',
    ]),
    method: 'Marinate 20 min in lemon, turmeric, garlic, and oregano. Air-fry 200°C for 13 min. Clean and aromatic. Pack with 2 chapatis.',
    shelfLifeTip: const Value('Fragrant and clean-tasting. [S]'),
    tags: const Value('lunch,simple,dry-pack,lemon,chicken'),
  ),

  // ==========================================
  // DINNER (20 Recipes) — Always 1 cup White Rice + 200g Chicken
  // ==========================================
  RecipesCompanion.insert(
    id: 'naatu_kozhi_kuzhambu_dinner',
    name: '1. Naatu Kozhi Kuzhambu Style (Coconut-Tomato Gravy + Rice)',
    tamilName: const Value('நாட்டுக்கோழி குழம்பு'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Mon'),
    calories: 618.0,
    proteinG: 68.0,
    carbsG: 60.0,
    fatG: 13.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g boiler chicken breast',
      '1 cup (200g) cooked white rice',
      '1 onion & 1 tomato',
      '3 tbsp ground coconut paste',
      'Spices & curry leaves',
      '1 tsp cooking oil',
    ]),
    method: 'Sauté onion-tomato-masala, add chicken, coconut paste + water, simmer 20 min. Serve over 1 cup hot white rice.',
    shelfLifeTip: const Value('Eaten fresh at home (8:15 PM). [S] Simple'),
    tags: const Value('dinner,simple,curry,chicken,rice'),
  ),
  RecipesCompanion.insert(
    id: 'pepper_garlic_chicken_dry_dinner',
    name: '2. Pepper Garlic Chicken Dry (Pan-Roast Pepper Garlic + Rice)',
    tamilName: const Value('பூண்டு மிளகு சிக்கன்'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Tue'),
    calories: 606.0,
    proteinG: 68.0,
    carbsG: 57.0,
    fatG: 12.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g boiler chicken breast',
      '1 cup cooked white rice',
      '2 tsp black pepper',
      '8 garlic cloves',
      'Curry leaves',
      '1 tsp oil',
    ]),
    method: 'Pan-roast or air-fry chicken with garlic and freshly crushed pepper. Simplest dinner. Serve with rice.',
    shelfLifeTip: const Value('Fastest dinner. [S] Simple'),
    tags: const Value('dinner,simple,pepper,garlic,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'chettinad_kozhi_curry',
    name: '3. Chettinad Kozhi Curry (Fresh Chettinad Spices + Rice)',
    tamilName: const Value('செட்டிநாடு கோழி கறி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Wed'),
    calories: 621.0,
    proteinG: 68.0,
    carbsG: 60.0,
    fatG: 13.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g boiler chicken',
      '1 cup cooked white rice',
      'Chettinad masala (fennel, pepper, cinnamon, star anise, red chili)',
      '1 onion & 1 tomato',
      '1 tsp oil',
    ]),
    method: 'Freshly grind spices, build aromatic gravy with onion-tomato base, simmer chicken 20 min. Serve over rice.',
    shelfLifeTip: const Value('Weekend / complex flavor. [C] Complex'),
    tags: const Value('dinner,complex,chettinad,curry,weekend'),
  ),
  RecipesCompanion.insert(
    id: 'tandoori_chicken_rice',
    name: '4. Tandoori Chicken + Rice (Air-Fried Tandoori Dinner)',
    tamilName: const Value('தந்தூரி சிக்கன் + சாதம்'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Thu'),
    calories: 636.0,
    proteinG: 70.0,
    carbsG: 60.0,
    fatG: 14.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken breast',
      '1 cup cooked white rice',
      '3 tbsp hung curd',
      '1 tbsp tandoori masala (MDH/Everest)',
      'Kashmiri chili powder',
      'Ginger-garlic & lemon',
    ]),
    method: 'Marinate 30 min. Air-fry 200°C for 18 min. Serve hot over 1 cup white rice.',
    shelfLifeTip: const Value('Air-fryer dinner. [S] Simple'),
    tags: const Value('dinner,simple,tandoori,air-fryer,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'butter_chicken_light',
    name: '5. Butter Chicken Style Lighter (Tomato-Curd Base + Rice)',
    tamilName: const Value('பட்டர் சிக்கன் (லைட்)'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Fri'),
    calories: 628.0,
    proteinG: 68.0,
    carbsG: 61.0,
    fatG: 14.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '1 onion & 3 tomatoes',
      '50g hung curd (no cream)',
      'Garam masala & Kashmiri chili',
      '1 tsp oil',
    ]),
    method: 'Blend onion-tomato base, cook with spices, add seared chicken and fold in hung curd (no heavy butter/cream). Serve with rice.',
    shelfLifeTip: const Value('Light restaurant-style. [C] Complex'),
    tags: const Value('dinner,complex,butter-chicken,curd,weekend'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_salna',
    name: '6. Chicken Salna (Chennai Street-Style Thin Gravy + Rice)',
    tamilName: const Value('சிக்கன் சால்னா'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Sat'),
    calories: 625.0,
    proteinG: 68.0,
    carbsG: 61.0,
    fatG: 14.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      'Onion, tomato, fennel, coconut paste, star anise',
      '1 tsp oil',
    ]),
    method: 'Thin fragrant Tamil salna gravy — pairs perfectly with rice. Simmer 18 min.',
    shelfLifeTip: const Value('Fragrant thin gravy. [S] Simple'),
    tags: const Value('dinner,simple,salna,curry,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'soy_ginger_chicken_rice',
    name: '7. Soy-Ginger Chicken on Rice (Asian High-Heat Stir-Fry)',
    tamilName: const Value('சோயா இஞ்சி சிக்கன்'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Sun'),
    calories: 626.0,
    proteinG: 68.0,
    carbsG: 62.0,
    fatG: 14.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '2 tbsp soy sauce (DMart)',
      '1-inch ginger (grated)',
      '2 garlic cloves',
      '1/2 tsp sesame oil',
      'Spring onion & 1 tsp oil',
    ]),
    method: 'High-heat stir-fry 8 min. Pour sizzling pan juices over rice. Top with spring onion.',
    shelfLifeTip: const Value('Asian pan juices. [S] Simple'),
    tags: const Value('dinner,simple,soy,ginger,asian'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_schezwan_stir_fry',
    name: '8. Chicken Schezwan Stir-Fry (Indo-Chinese Spicy Chicken + Rice)',
    tamilName: const Value('செஸ்வான் சிக்கன்'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 617.0,
    proteinG: 68.0,
    carbsG: 59.0,
    fatG: 13.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken breast',
      '1 cup cooked white rice',
      '1 tsp schezwan sauce (DMart)',
      'Capsicum & spring onion',
      'Soy sauce & garlic',
      '1 tsp oil',
    ]),
    method: 'High-heat flash stir-fry, add schezwan sauce in last minute. Serve hot over white rice.',
    shelfLifeTip: const Value('Indo-Chinese spice. [S] Simple'),
    tags: const Value('dinner,simple,schezwan,indo-chinese,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_peanut_kuzhambu',
    name: '9. Chicken Peanut Kuzhambu (Ground Peanut Gravy + Rice)',
    tamilName: const Value('வேர்க்கடலை சிக்கன் குழம்பு'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 634.0,
    proteinG: 68.0,
    carbsG: 62.0,
    fatG: 15.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '30g peanuts (boiled, ground to paste)',
      'Onion, tomato, chili',
      '1 tsp oil',
    ]),
    method: 'Use peanut paste as thickener instead of coconut. Earthy, rich, nutty gravy. Serve with rice.',
    shelfLifeTip: const Value('Nutty gravy. [C] Complex'),
    tags: const Value('dinner,complex,peanut,curry,weekend'),
  ),
  RecipesCompanion.insert(
    id: 'coconut_milk_chicken_curry',
    name: '10. Coconut Milk Chicken Curry (Kozhi Thengai Paal + Rice)',
    tamilName: const Value('தேங்காய்ப்பால் கோழி கறி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 647.0,
    proteinG: 68.0,
    carbsG: 63.0,
    fatG: 16.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '100 ml canned coconut milk (DMart)',
      'Onion, tomato, spices',
      '1 tsp oil',
    ]),
    method: 'Build onion-tomato base, add chicken and spices, stir in coconut milk last — never boil hard once added. Serve with rice.',
    shelfLifeTip: const Value('Creamy coconut gravy. [S] Simple'),
    tags: const Value('dinner,simple,coconut-milk,creamy,curry'),
  ),
  RecipesCompanion.insert(
    id: 'pepper_tamarind_chicken',
    name: '11. Pepper Tamarind Chicken (4-Ingredient Peppery Gravy + Rice)',
    tamilName: const Value('மிளகு புளி சிக்கன்'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 616.0,
    proteinG: 68.0,
    carbsG: 59.0,
    fatG: 13.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      'Tamarind water (small ball)',
      '2 tsp black pepper',
      '2 dried red chilies',
      '1 tsp oil',
    ]),
    method: 'Thin peppery-sour gravy. Simmer chicken 15 min till tender. Serve over rice.',
    shelfLifeTip: const Value('4 ingredients. [S] Simple'),
    tags: const Value('dinner,simple,quick,tamarind,pepper'),
  ),
  RecipesCompanion.insert(
    id: 'tomato_chicken_curry',
    name: '12. Tomato Chicken Curry (3-Tomato Beginner-Proof Gravy + Rice)',
    tamilName: const Value('தக்காளி சிக்கன் கறி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 620.0,
    proteinG: 68.0,
    carbsG: 61.0,
    fatG: 13.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '3 large tomatoes (chopped)',
      '1 onion',
      'Garam masala & chili powder',
      '1 tsp oil',
    ]),
    method: 'Pressure-cook 3 whistles or simmer 20 min in fresh tomato gravy. Very forgiving. Serve with rice.',
    shelfLifeTip: const Value('Beginner-proof. [S] Simple'),
    tags: const Value('dinner,simple,tomato,curry,easy'),
  ),
  RecipesCompanion.insert(
    id: 'ketchup_chicken_curry',
    name: '13. Ketchup Chicken Curry (Quick Tomato Ketchup Base + Rice)',
    tamilName: const Value('கெட்சப் சிக்கன் கறி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 617.0,
    proteinG: 68.0,
    carbsG: 59.0,
    fatG: 13.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '3 tbsp tomato ketchup (DMart)',
      '1 onion & garlic',
      '1/2 tsp chili powder',
      '1 tsp oil',
    ]),
    method: 'Sauté onion-garlic, add ketchup + spice, add chicken and 50 ml water, simmer 15 min. Serve with rice.',
    shelfLifeTip: const Value('Fastest curry. [S] Simple'),
    tags: const Value('dinner,simple,quick,ketchup,curry'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_egg_kuzhambu_dinner',
    name: '14. Chicken Egg Kuzhambu (200g Chicken + 2 Boiled Eggs + Rice)',
    tamilName: const Value('சிக்கன் முட்டை குழம்பு'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 630.0,
    proteinG: 69.0,
    carbsG: 62.0,
    fatG: 14.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '2 boiled eggs',
      'Onion, tomato, spices',
      '1 tsp oil',
    ]),
    method: 'Build normal chicken curry, add 2 boiled eggs whole in last 5 min to absorb the rich gravy. Serve with rice.',
    shelfLifeTip: const Value('Double protein hit. [S] Simple'),
    tags: const Value('dinner,simple,high-protein,eggs,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_spinach_curry',
    name: '15. Chicken Spinach Curry (Iron-Rich Spinach + Chicken + Rice)',
    tamilName: const Value('சிக்கன் பாலக் கறி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 630.0,
    proteinG: 68.0,
    carbsG: 62.0,
    fatG: 14.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '80g fresh spinach (chopped)',
      'Onion, tomato, spices',
      '1 tsp oil',
    ]),
    method: 'Cook chicken in onion-tomato masala, add chopped spinach only in last 3 min. Wilts fast and preserves nutrients. Serve with rice.',
    shelfLifeTip: const Value('Iron + micronutrients. [S] Simple'),
    tags: const Value('dinner,simple,spinach,greens,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'thayir_kozhi_curd_chicken',
    name: '16. Thayir Kozhi (Curd-Based Tangy Chicken Curry + Rice)',
    tamilName: const Value('தயிர் கோழி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekend'),
    calories: 640.0,
    proteinG: 69.0,
    carbsG: 61.0,
    fatG: 15.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '120g whisked curd',
      'Mild spices, onion',
      '1 tsp oil',
    ]),
    method: 'Cook chicken in onion-spice base, take off heat, stir in curd slowly. Never boil once curd is added. Serve with rice.',
    shelfLifeTip: const Value('Tangy comfort food. [C] Complex'),
    tags: const Value('dinner,complex,curd,tangy,weekend'),
  ),
  RecipesCompanion.insert(
    id: 'mint_chicken_pudina',
    name: '17. Mint Chicken Pudina Kozhi (Fresh Mint Paste + Rice)',
    tamilName: const Value('புதினா கோழி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 617.0,
    proteinG: 68.0,
    carbsG: 59.0,
    fatG: 13.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '50g fresh mint',
      'Green chili, ginger, onion',
      '1 tsp oil',
    ]),
    method: 'Blend mint + chili + ginger to smooth paste. Use as marinade and sauce base. Simmer chicken 15 min. Serve with rice.',
    shelfLifeTip: const Value('Bright mint flavor. [S] Simple'),
    tags: const Value('dinner,simple,mint,fresh,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_capsicum_masala',
    name: '18. Chicken Capsicum Masala (Bell Pepper Base Curry + Rice)',
    tamilName: const Value('குடைமிளகாய் சிக்கன் மசாலா'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 622.0,
    proteinG: 68.0,
    carbsG: 61.0,
    fatG: 13.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '2 capsicums (chopped)',
      'Onion, tomato, masala',
      '1 tsp oil',
    ]),
    method: 'Sauté capsicum soft, build onion-tomato masala, add chicken, simmer 15 min. Serve over rice.',
    shelfLifeTip: const Value('Crunchy capsicum. [S] Simple'),
    tags: const Value('dinner,simple,capsicum,curry,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'chicken_mushroom_stir_fry',
    name: '19. Chicken Mushroom Stir-Fry (Soy Sauce Stir-Fry + Rice)',
    tamilName: const Value('சிக்கன் காளான் வறுவல்'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 614.0,
    proteinG: 68.0,
    carbsG: 58.0,
    fatG: 13.0,
    fiberG: const Value(5.0),
    ingredientsJson: jsonEncode([
      '120g chicken + 120g mushrooms',
      '1 cup cooked white rice',
      '1 tbsp soy sauce (DMart)',
      'Garlic & black pepper',
      '1 tsp oil',
    ]),
    method: 'Stir-fry chicken and mushrooms together with soy sauce. Mushrooms release and reabsorb liquid. Serve over rice.',
    shelfLifeTip: const Value('Earthy and lean. [S] Simple'),
    tags: const Value('dinner,simple,mushroom,soy,chicken'),
  ),
  RecipesCompanion.insert(
    id: 'vinegar_garlic_chicken_curry',
    name: '20. Vinegar Garlic Chicken Curry (Goan-Style Garlic Chili + Rice)',
    tamilName: const Value('வினிகர் பூண்டு சிக்கன் கறி'),
    mealSlot: 'dinner',
    dayOfWeek: const Value('Weekday'),
    calories: 618.0,
    proteinG: 68.0,
    carbsG: 60.0,
    fatG: 13.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '200g chicken',
      '1 cup cooked white rice',
      '2 tsp vinegar (DMart)',
      '8 garlic cloves (sliced)',
      '2 dried red chilies, tomato',
      '1 tsp oil',
    ]),
    method: 'Sauté garlic golden, add vinegar, tomato, and dried chilies. Add chicken, thin gravy, simmer 15 min. Serve with rice.',
    shelfLifeTip: const Value('Goan-inspired tangy gravy. [S] Simple'),
    tags: const Value('dinner,simple,vinegar,garlic,curry'),
  ),

  // ==========================================
  // SNACKS (30 Recipes) — Real Diet & High-Protein Snacks
  // ==========================================
  // Section A: Morning / College
  RecipesCompanion.insert(
    id: 'masala_peanuts',
    name: '1. Masala Peanuts (Roasted Peanuts with Curry Leaves)',
    tamilName: const Value('மசாலா வேர்க்கடலை'),
    mealSlot: 'snack',
    calories: 230.0,
    proteinG: 10.0,
    carbsG: 8.0,
    fatG: 18.0,
    fiberG: const Value(3.0),
    ingredientsJson: jsonEncode([
      '40g roasted peanuts',
      'Curry leaves',
      'Chili powder & turmeric',
      '1/2 tsp cooking oil',
      'Salt',
    ]),
    method: 'Dry roast peanuts in pan with 1/2 tsp oil, curry leaves, chili powder, and turmeric. Store in carry pouch for college.',
    shelfLifeTip: const Value('College carry snack. No spoilage.'),
    tags: const Value('snack,peanuts,college-carry'),
  ),
  RecipesCompanion.insert(
    id: 'peanut_chikki',
    name: '2. Chikki (Peanut Jaggery Brittle)',
    tamilName: const Value('வேர்க்கடலை சிக்கி'),
    mealSlot: 'snack',
    calories: 175.0,
    proteinG: 8.0,
    carbsG: 20.0,
    fatG: 8.0,
    fiberG: const Value(2.0),
    ingredientsJson: jsonEncode([
      '25g roasted peanuts',
      '20g jaggery',
    ]),
    method: 'Melt jaggery to syrup, mix in roasted peanuts, roll flat on greased board, let cool and snap into pieces.',
    shelfLifeTip: const Value('Pre-workout energy / college.'),
    tags: const Value('snack,pre-workout,sweet,chikki'),
  ),
  RecipesCompanion.insert(
    id: 'trail_mix_carry',
    name: '3. Trail Mix Carry Pouch (Peanuts + Seeds + Roasted Gram)',
    tamilName: const Value('டிரெயில் மிக்ஸ்'),
    mealSlot: 'snack',
    calories: 210.0,
    proteinG: 10.0,
    carbsG: 20.0,
    fatG: 11.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '20g roasted peanuts',
      '10g pumpkin seeds',
      '10g roasted chana dal',
      'Crispy curry leaves',
    ]),
    method: 'Toss roasted ingredients with salt and crushed curry leaves. Store in small pouch.',
    shelfLifeTip: const Value('Anytime carry. Zero spoilage.'),
    tags: const Value('snack,trail-mix,college,seeds'),
  ),
  RecipesCompanion.insert(
    id: 'sprouted_moong_chaat',
    name: '4. Sprouted Moong Chaat (Fresh Sprouted Moong Salad)',
    tamilName: const Value('முளைகட்டிய பாசிப்பயறு சாட்'),
    mealSlot: 'snack',
    calories: 150.0,
    proteinG: 11.0,
    carbsG: 25.0,
    fatG: 1.0,
    fiberG: const Value(6.0),
    ingredientsJson: jsonEncode([
      '60g sprouted green moong',
      'Finely chopped onion & tomato',
      'Fresh lemon juice',
      'Chaat masala',
    ]),
    method: 'Toss sprouted green moong with chopped onion, tomato, lemon juice, and chaat masala.',
    shelfLifeTip: const Value('Home morning snack. High fiber.'),
    tags: const Value('snack,sprouts,high-fiber,clean'),
  ),
  RecipesCompanion.insert(
    id: 'vellam_pottukadalai_urundai',
    name: '5. Vellam Pottukadalai Urundai (Roasted Gram Jaggery Laddu)',
    tamilName: const Value('பொட்டுக் கடலை உருண்டை'),
    mealSlot: 'snack',
    calories: 160.0,
    proteinG: 4.0,
    carbsG: 28.0,
    fatG: 4.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '40g roasted gram (pottukadalai)',
      '25g jaggery',
      'Cardamom powder',
    ]),
    method: 'Melt jaggery to hard string consistency, fold in roasted gram and cardamom, shape into round balls while warm.',
    shelfLifeTip: const Value('Pre-workout fast carbs.'),
    tags: const Value('snack,energy,sweet,traditional'),
  ),

  // Section B: Protein Drinks & Smoothies
  RecipesCompanion.insert(
    id: 'whey_banana_shake',
    name: '6. Whey Banana Shake (Post-Workout Protein Shake)',
    tamilName: const Value('வே பனானா ஷேக்'),
    mealSlot: 'snack',
    calories: 220.0,
    proteinG: 25.0,
    carbsG: 24.0,
    fatG: 3.0,
    fiberG: const Value(2.0),
    ingredientsJson: jsonEncode([
      '1/2 scoop whey isolate (15g)',
      '1 medium banana (120g)',
      '150 ml whole milk',
    ]),
    method: 'Blend whey protein, sliced banana, and milk with ice until smooth and frothy.',
    shelfLifeTip: const Value('Post-workout fast recovery.'),
    tags: const Value('snack,shake,post-workout,whey'),
  ),
  RecipesCompanion.insert(
    id: 'peanut_butter_banana_shake',
    name: '7. Peanut Butter Banana Shake (Creamy PB Shake)',
    tamilName: const Value('பீனட் பட்டர் பனானா ஷேக்'),
    mealSlot: 'snack',
    calories: 215.0,
    proteinG: 18.0,
    carbsG: 24.0,
    fatG: 6.0,
    fiberG: const Value(3.0),
    ingredientsJson: jsonEncode([
      '1 banana (120g)',
      '1 tbsp natural peanut butter (15g)',
      '200 ml whole milk',
    ]),
    method: 'Blend banana, natural unsweetened peanut butter, and cold milk until thick and creamy.',
    shelfLifeTip: const Value('Post-workout / evening.'),
    tags: const Value('snack,shake,protein,peanut-butter'),
  ),
  RecipesCompanion.insert(
    id: 'high_protein_mango_lassi',
    name: '8. High-Protein Mango Lassi (Curd + Whey + Fresh Mango)',
    tamilName: const Value('மேங்கோ லஸ்ஸி'),
    mealSlot: 'snack',
    calories: 190.0,
    proteinG: 16.0,
    carbsG: 26.0,
    fatG: 3.0,
    fiberG: const Value(2.0),
    ingredientsJson: jsonEncode([
      '100g fresh curd',
      '1/2 scoop whey isolate (15g)',
      '1 small mango pulp (100g)',
      'Crushed ice',
    ]),
    method: 'Blend fresh curd, whey protein powder, and fresh mango pulp with crushed ice.',
    shelfLifeTip: const Value('Afternoon refreshing treat.'),
    tags: const Value('snack,lassi,protein,mango'),
  ),
  RecipesCompanion.insert(
    id: 'spiced_buttermilk_mor',
    name: '9. Spiced Buttermilk / Neer Mor (Ginger Curry Leaf Cooler)',
    tamilName: const Value('நீர் மோர்'),
    mealSlot: 'snack',
    calories: 60.0,
    proteinG: 3.0,
    carbsG: 5.0,
    fatG: 2.0,
    fiberG: const Value(0.0),
    ingredientsJson: jsonEncode([
      '80g fresh curd',
      '200 ml cold water',
      'Curry leaves & crushed ginger',
      'Green chili & salt',
    ]),
    method: 'Whisk curd and water until frothy. Add crushed ginger, green chili, curry leaves, and salt.',
    shelfLifeTip: const Value('Digestion & hydration in TN heat.'),
    tags: const Value('snack,hydration,buttermilk,cooling'),
  ),
  RecipesCompanion.insert(
    id: 'oat_curd_shake',
    name: '10. Oat Curd Shake (Savory Oat Yogurt Drink)',
    tamilName: const Value('ஓட்ஸ் தயிர் ஷேக்'),
    mealSlot: 'snack',
    calories: 175.0,
    proteinG: 13.0,
    carbsG: 22.0,
    fatG: 4.0,
    fiberG: const Value(2.0),
    ingredientsJson: jsonEncode([
      '20g rolled oats (powdered dry)',
      '100g curd',
      'Cold water',
      '5g jaggery',
    ]),
    method: 'Blend powdered oats, fresh curd, cold water, and a touch of jaggery until smooth.',
    shelfLifeTip: const Value('Morning or post-workout.'),
    tags: const Value('snack,shake,oats,curd'),
  ),

  // Section C: Protein Desserts
  RecipesCompanion.insert(
    id: 'protein_brownie_bites',
    name: '11. Protein Brownie Bites (No-Bake Cocoa PB Whey Balls)',
    tamilName: const Value('புரோட்டீன் பிரவுனி பைட்ஸ்'),
    mealSlot: 'snack',
    calories: 220.0,
    proteinG: 18.0,
    carbsG: 28.0,
    fatG: 6.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '30g natural peanut butter',
      '20g cocoa powder (unsweetened)',
      '1/2 scoop whey isolate (15g)',
      '20g jaggery',
      '1 tbsp oats & splash of milk',
    ]),
    method: 'Mix all into thick dough, shape into 4 fudgy balls, refrigerate 30 min. Makes 4 balls total.',
    shelfLifeTip: const Value('Fudgy dessert. [C] Needs fridge set.'),
    tags: const Value('snack,dessert,chocolate,no-bake,protein'),
  ),
  RecipesCompanion.insert(
    id: 'banana_nice_cream',
    name: '12. Banana Nice Cream (Protein Soft-Serve "Ice Cream")',
    tamilName: const Value('பனானா நைஸ் கிரீம்'),
    mealSlot: 'snack',
    calories: 185.0,
    proteinG: 16.0,
    carbsG: 22.0,
    fatG: 4.0,
    fiberG: const Value(3.0),
    ingredientsJson: jsonEncode([
      '2 frozen bananas (240g)',
      '1/2 scoop whey protein (15g)',
      'Splash of milk',
    ]),
    method: 'Freeze bananas overnight. Blend frozen with whey and splash of milk until creamy soft-serve consistency. Eat immediately.',
    shelfLifeTip: const Value('Post-workout treat. [S] Simple'),
    tags: const Value('snack,dessert,ice-cream,banana'),
  ),
  RecipesCompanion.insert(
    id: 'hung_curd_ice_cream',
    name: '13. Hung Curd Ice Cream (Cardamom Frozen Yogurt)',
    tamilName: const Value('ஹங் கர்ட் ஐஸ்கிரீம்'),
    mealSlot: 'snack',
    calories: 190.0,
    proteinG: 17.0,
    carbsG: 20.0,
    fatG: 6.0,
    fiberG: const Value(0.0),
    ingredientsJson: jsonEncode([
      '150g hung curd (strained)',
      '1 tbsp jaggery (15g)',
      'Pinch of cardamom powder',
    ]),
    method: 'Whisk hung curd with jaggery and cardamom. Freeze for 4 hours, stirring once after 2 hours to break ice crystals.',
    shelfLifeTip: const Value('High-protein creamy frozen yogurt. [C]'),
    tags: const Value('snack,frozen-yogurt,high-protein,dessert'),
  ),
  RecipesCompanion.insert(
    id: 'chocolate_oat_protein_balls',
    name: '14. Chocolate Oat Protein Balls (No-Bake Snack Bites)',
    tamilName: const Value('சாக்லேட் ஓட்ஸ் புரோட்டீன் உருண்டை'),
    mealSlot: 'snack',
    calories: 195.0,
    proteinG: 18.0,
    carbsG: 26.0,
    fatG: 5.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '30g rolled oats',
      '15g cocoa powder',
      '1/2 scoop whey',
      '20g peanut butter',
      '15g jaggery',
      'Splash of milk',
    ]),
    method: 'Mix into dough, roll into 5 snack balls, refrigerate 1 hour.',
    shelfLifeTip: const Value('Makes 5 balls. [C] Set in fridge.'),
    tags: const Value('snack,protein-balls,oats,chocolate'),
  ),
  RecipesCompanion.insert(
    id: 'baked_oat_protein_muffin',
    name: '15. Baked Oat Protein Muffin (Air-Fryer Single-Serve Muffin)',
    tamilName: const Value('ஓட்ஸ் புரோட்டீன் மஃபின்'),
    mealSlot: 'snack',
    calories: 180.0,
    proteinG: 15.0,
    carbsG: 22.0,
    fatG: 5.0,
    fiberG: const Value(3.0),
    ingredientsJson: jsonEncode([
      '30g rolled oats',
      '1 whole egg',
      '1/2 scoop whey',
      '1 small banana (60g)',
      'Pinch of baking powder',
    ]),
    method: 'Blend ingredients, pour into muffin mold, air-fry at 180°C for 12 min or bake 175°C for 15 min.',
    shelfLifeTip: const Value('Air-fryer muffin. [C]'),
    tags: const Value('snack,air-fryer,muffin,baked'),
  ),

  // Section D: Tamil Nadu Sundal & Legumes
  RecipesCompanion.insert(
    id: 'pachai_payaru_sundal',
    name: '16. Pachai Payaru Sundal (Whole Green Moong Sundal)',
    tamilName: const Value('பச்சை பயறு சுண்டல்'),
    mealSlot: 'snack',
    calories: 170.0,
    proteinG: 12.0,
    carbsG: 26.0,
    fatG: 3.0,
    fiberG: const Value(7.0),
    ingredientsJson: jsonEncode([
      '60g whole green moong (cooked)',
      'Mustard & curry leaves',
      '1 tbsp grated coconut',
      '1 tsp oil & salt',
    ]),
    method: 'Temper mustard and curry leaves in 1 tsp oil, toss cooked moong with fresh coconut and salt.',
    shelfLifeTip: const Value('Anytime snack. High fiber.'),
    tags: const Value('snack,sundal,moong,high-fiber'),
  ),
  RecipesCompanion.insert(
    id: 'kadalai_paruppu_sundal',
    name: '17. Kadalai Paruppu Sundal (Chana Dal Sundal)',
    tamilName: const Value('கடலை பருப்பு சுண்டல்'),
    mealSlot: 'snack',
    calories: 175.0,
    proteinG: 11.0,
    carbsG: 28.0,
    fatG: 4.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '60g chana dal (soaked & cooked)',
      'Tempering spices',
      '1 tbsp coconut',
      '1 tsp oil',
    ]),
    method: 'Temper spices in oil, add boiled chana dal, stir-fry with coconut until dry.',
    shelfLifeTip: const Value('Anytime high-protein sundal.'),
    tags: const Value('snack,sundal,chana-dal,fiber'),
  ),
  RecipesCompanion.insert(
    id: 'pattani_sundal',
    name: '18. Pattani Sundal (Dried Green Peas Sundal)',
    tamilName: const Value('பட்டாணி சுண்டல்'),
    mealSlot: 'snack',
    calories: 165.0,
    proteinG: 10.0,
    carbsG: 27.0,
    fatG: 3.0,
    fiberG: const Value(8.0),
    ingredientsJson: jsonEncode([
      '60g dried green peas (cooked)',
      'Tempering spices',
      '1 tbsp coconut',
      '1 tsp oil',
    ]),
    method: 'Temper spices in 1 tsp oil, toss cooked dried green peas with grated coconut for 3 min.',
    shelfLifeTip: const Value('Traditional beach/temple sundal.'),
    tags: const Value('snack,sundal,pattani,traditional'),
  ),
  RecipesCompanion.insert(
    id: 'kala_chana_sundal',
    name: '19. Kala Chana Sundal (Black Chickpea Iron-Rich Sundal)',
    tamilName: const Value('கருப்பு கடலை சுண்டல்'),
    mealSlot: 'snack',
    calories: 155.0,
    proteinG: 11.0,
    carbsG: 24.0,
    fatG: 3.0,
    fiberG: const Value(9.0),
    ingredientsJson: jsonEncode([
      '60g black chickpeas (boiled)',
      'Tempering spices',
      '1 tbsp coconut',
      '1 tsp oil',
    ]),
    method: 'Temper mustard and red chili in 1 tsp oil, toss boiled black chana and fresh coconut. Highest iron snack.',
    shelfLifeTip: const Value('Highest iron content.'),
    tags: const Value('snack,sundal,kala-chana,iron'),
  ),
  RecipesCompanion.insert(
    id: 'payaru_thayir_pachadi',
    name: '20. Payaru Thayir Pachadi (Sprouted Moong & Curd Raita Bowl)',
    tamilName: const Value('பயறு தயிர் பச்சடி'),
    mealSlot: 'snack',
    calories: 130.0,
    proteinG: 9.0,
    carbsG: 16.0,
    fatG: 3.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '50g sprouted green moong',
      '100g fresh curd',
      'Roasted cumin & salt',
    ]),
    method: 'Mix fresh sprouted moong into whisked curd with roasted cumin powder and salt.',
    shelfLifeTip: const Value('Afternoon at home.'),
    tags: const Value('snack,raita,curd,sprouts'),
  ),

  // Section E: Light Sweet / Energy Snacks
  RecipesCompanion.insert(
    id: 'ellu_urundai',
    name: '21. Ellu Urundai (Toasted Sesame & Jaggery Calcium Ball)',
    tamilName: const Value('எள்ளு உருண்டை'),
    mealSlot: 'snack',
    calories: 140.0,
    proteinG: 3.0,
    carbsG: 18.0,
    fatG: 7.0,
    fiberG: const Value(2.0),
    ingredientsJson: jsonEncode([
      '20g sesame seeds (toasted)',
      '20g jaggery',
      'Cardamom powder',
    ]),
    method: 'Melt jaggery, mix in toasted sesame seeds, shape into round balls while warm.',
    shelfLifeTip: const Value('Pre-workout calcium booster.'),
    tags: const Value('snack,energy,sesame,calcium'),
  ),
  RecipesCompanion.insert(
    id: 'kambu_koozh',
    name: '22. Kambu Koozh (Cold Fermented Pearl Millet Porridge)',
    tamilName: const Value('கம்பங்கூழ்'),
    mealSlot: 'snack',
    calories: 150.0,
    proteinG: 4.0,
    carbsG: 28.0,
    fatG: 4.0,
    fiberG: const Value(3.0),
    ingredientsJson: jsonEncode([
      '40g kambu flour',
      'Water & salt',
      'Small onion & green chili',
    ]),
    method: 'Cook kambu flour into thick porridge, ferment overnight, serve cold with chopped onion and buttermilk.',
    shelfLifeTip: const Value('Hot-day summer body cooler.'),
    tags: const Value('snack,cooling,millet,fermented'),
  ),
  RecipesCompanion.insert(
    id: 'air_fried_nendran_chips',
    name: '23. Air-Fried Nendran Chips (Crispy Raw Banana Chips)',
    tamilName: const Value('ஏர்-பிரை நேந்திரம் சிப்ஸ்'),
    mealSlot: 'snack',
    calories: 155.0,
    proteinG: 3.0,
    carbsG: 22.0,
    fatG: 6.0,
    fiberG: const Value(3.0),
    ingredientsJson: jsonEncode([
      '1 raw banana (100g)',
      'Pinch of salt & chili',
      '1/2 tsp oil',
    ]),
    method: 'Slice raw banana thin, toss with salt and chili, air-fry at 180°C for 15 min until crispy.',
    shelfLifeTip: const Value('Crispy evening snack.'),
    tags: const Value('snack,chips,air-fryer,crunchy'),
  ),
  RecipesCompanion.insert(
    id: 'masala_corn',
    name: '24. Masala Corn (Steamed Sweet Corn with Chaat Masala & Lemon)',
    tamilName: const Value('மசாலா சோளம்'),
    mealSlot: 'snack',
    calories: 165.0,
    proteinG: 5.0,
    carbsG: 30.0,
    fatG: 4.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '1 cup sweet corn kernels (boiled)',
      'Black pepper & chaat masala',
      'Fresh lemon juice',
      'Salt',
    ]),
    method: 'Steam corn kernels, toss hot with chaat masala, pepper, and fresh lime juice.',
    shelfLifeTip: const Value('Evening / post-dinner light snack.'),
    tags: const Value('snack,corn,light,chaat'),
  ),
  RecipesCompanion.insert(
    id: 'ragi_malt_kanji',
    name: '25. Ragi Malt / Kezhvaragu Kanji (Warm Ragi Milk with Cardamom)',
    tamilName: const Value('கேழ்வரகு கஞ்சி'),
    mealSlot: 'snack',
    calories: 180.0,
    proteinG: 5.0,
    carbsG: 32.0,
    fatG: 5.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '30g ragi (finger millet) flour',
      '250 ml whole milk',
      '8g jaggery',
      'Cardamom powder',
    ]),
    method: 'Whisk ragi flour in water without lumps, cook until glossy, stir in hot milk, jaggery, and cardamom.',
    shelfLifeTip: const Value('Evening / recovery calcium drink.'),
    tags: const Value('snack,ragi,calcium,recovery'),
  ),

  // Section F: High-Protein Savory Snacks
  RecipesCompanion.insert(
    id: 'pepper_egg_white_bites',
    name: '26. Pepper Egg White Bites (3 Boiled Egg Whites + Pepper)',
    tamilName: const Value('முட்டை வெள்ளைக்கரு பைட்ஸ்'),
    mealSlot: 'snack',
    calories: 160.0,
    proteinG: 13.0,
    carbsG: 3.0,
    fatG: 11.0,
    fiberG: const Value(1.0),
    ingredientsJson: jsonEncode([
      '3 boiled egg whites',
      '1/4 tsp black pepper',
      'Chaat masala & salt',
    ]),
    method: 'Slice hard-boiled egg whites, sprinkle with fresh black pepper and chaat masala.',
    shelfLifeTip: const Value('Pure lean protein top-up.'),
    tags: const Value('snack,egg-white,pure-protein,quick'),
  ),
  RecipesCompanion.insert(
    id: 'soya_chilli_bites',
    name: '27. Soya Chilli Bites (Indo-Chinese Flash Stir-Fry)',
    tamilName: const Value('சோயா சில்லி பைட்ஸ்'),
    mealSlot: 'snack',
    calories: 200.0,
    proteinG: 17.0,
    carbsG: 18.0,
    fatG: 8.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '40g dry soya chunks (squeezed dry)',
      'Soy sauce & red chili sauce',
      'Garlic',
      '1/2 tsp oil',
    ]),
    method: 'Rehydrate and squeeze soya chunks dry. Flash stir-fry with garlic, soy sauce, and red chili sauce.',
    shelfLifeTip: const Value('Evening protein snack at home.'),
    tags: const Value('snack,soya,high-protein,indo-chinese'),
  ),
  RecipesCompanion.insert(
    id: 'hung_curd_peanut_dip',
    name: '28. Hung Curd + Peanut Dip with Veg (Cucumber & Dip)',
    tamilName: const Value('தயிர் வேர்க்கடலை டிப்'),
    mealSlot: 'snack',
    calories: 195.0,
    proteinG: 15.0,
    carbsG: 12.0,
    fatG: 10.0,
    fiberG: const Value(2.0),
    ingredientsJson: jsonEncode([
      '100g hung curd',
      '10g crushed peanuts',
      'Roasted cumin & salt',
      '100g cucumber sticks',
    ]),
    method: 'Mix hung curd with crushed peanuts, cumin, and salt. Serve as high-protein dip with cucumber sticks.',
    shelfLifeTip: const Value('Afternoon snack at home.'),
    tags: const Value('snack,dip,protein,cucumber'),
  ),
  RecipesCompanion.insert(
    id: 'paneer_tikka_bites',
    name: '29. Paneer Tikka Bites (Air-Fried Spiced Paneer)',
    tamilName: const Value('பன்னீர் டிக்கா பைட்ஸ்'),
    mealSlot: 'snack',
    calories: 185.0,
    proteinG: 13.0,
    carbsG: 14.0,
    fatG: 9.0,
    fiberG: const Value(0.0),
    ingredientsJson: jsonEncode([
      '80g paneer cubes',
      'Chili powder & turmeric',
      'Lemon juice & ginger-garlic',
    ]),
    method: 'Toss paneer in spices, air-fry at 200°C for 8 min until edges are golden.',
    shelfLifeTip: const Value('Quick home snack.'),
    tags: const Value('snack,air-fryer,paneer,tikka'),
  ),
  RecipesCompanion.insert(
    id: 'oats_khichdi_bowl',
    name: '30. Oats Khichdi (Light Savory Moong & Oat Bowl)',
    tamilName: const Value('ஓட்ஸ் கிச்சடி'),
    mealSlot: 'snack',
    calories: 195.0,
    proteinG: 16.0,
    carbsG: 18.0,
    fatG: 7.0,
    fiberG: const Value(4.0),
    ingredientsJson: jsonEncode([
      '30g rolled oats',
      '15g split moong dal',
      'Mustard, curry leaves, grated carrot',
      '1 tsp oil',
    ]),
    method: 'Simmer moong dal and oats together with tempered mustard, curry leaves, and carrot until soft.',
    shelfLifeTip: const Value('Light evening savory bowl.'),
    tags: const Value('snack,khichdi,savory,light'),
  ),
];
