import 'dart:convert';
import 'package:drift/drift.dart';
import 'app_database.dart';

class SeedData {
  static Future<void> seedInitialData(AppDatabase db) async {
    // 1. Seed Default User if not exists
    final existingUser = await db.getUserProfile();
    if (existingUser == null) {
      await db.saveUserProfile(
        UsersCompanion.insert(
          id: const Value('default_user'),
          heightCm: const Value(160.0),
          weightKg: const Value(62.0),
          age: const Value(21),
          activityLevel: const Value('moderate'),
          calorieTarget: const Value(2350),
          proteinTargetG: const Value(155.0),
          carbTargetG: const Value(260.0),
          fatTargetG: const Value(70.0),
          fiberTargetG: const Value(30.0),
          waterTargetMl: const Value(3000),
          stepsTarget: const Value(10000),
        ),
      );
    }

    // 2. Seed Food Items from ICMR-NIN & Tamil Nadu manual
    final existingFoods = await db.searchFoodItems('');
    if (existingFoods.isEmpty) {
      await db.insertFoodItemsBatch([
        // Proteins
        const FoodItemsCompanion(
          id: Value('naatu_kozhi_raw'),
          name: Value('Country Chicken (Naatu Kozhi, Raw)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(128.0),
          proteinG: Value(21.5),
          carbsG: Value(0.0),
          fatG: Value(4.0),
          fiberG: Value(0.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('chicken_breast_boneless'),
          name: Value('Chicken Breast (Boneless, Raw)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(130.0),
          proteinG: Value(24.0),
          carbsG: Value(0.0),
          fatG: Value(3.5),
          fiberG: Value(0.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('whole_egg_boiled'),
          name: Value('Whole Egg (Boiled/Cooked)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(1.0),
          servingUnit: Value('egg (50g)'),
          calories: Value(78.0),
          proteinG: Value(6.3),
          carbsG: Value(0.6),
          fatG: Value(5.3),
          fiberG: Value(0.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('egg_white'),
          name: Value('Egg White (Cooked)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(1.0),
          servingUnit: Value('white (33g)'),
          calories: Value(17.0),
          proteinG: Value(3.6),
          carbsG: Value(0.2),
          fatG: Value(0.1),
          fiberG: Value(0.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('soya_chunks_dry'),
          name: Value('Soya Chunks (Dry)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(50.0),
          servingUnit: Value('g'),
          calories: Value(172.0),
          proteinG: Value(26.0),
          carbsG: Value(16.5),
          fatG: Value(0.5),
          fiberG: Value(6.5),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('white_chickpeas_sundal'),
          name: Value('White Chickpeas (Vella Kadalai, Boiled)'),
          brand: Value(null),
          category: Value('legume'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(164.0),
          proteinG: Value(8.9),
          carbsG: Value(27.4),
          fatG: Value(2.6),
          fiberG: Value(7.6),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('paneer_fresh'),
          name: Value('Paneer (Fresh Indian Cottage Cheese)'),
          brand: Value(null),
          category: Value('dairy'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(265.0),
          proteinG: Value(18.3),
          carbsG: Value(2.5),
          fatG: Value(20.8),
          fiberG: Value(0.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('whey_protein_isolate'),
          name: Value('Whey Protein Powder (1 Scoop)'),
          brand: Value('Generic'),
          category: Value('supplement'),
          servingSize: Value(1.0),
          servingUnit: Value('scoop (30g)'),
          calories: Value(120.0),
          proteinG: Value(24.0),
          carbsG: Value(2.0),
          fatG: Value(1.5),
          fiberG: Value(0.0),
          source: Value('open_food_facts'),
          isGeneric: Value(true),
        ),

        // Carbs & Grains
        const FoodItemsCompanion(
          id: Value('wheat_chapati'),
          name: Value('Whole Wheat Chapati / Roti'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(1.0),
          servingUnit: Value('chapati (~40g)'),
          calories: Value(120.0),
          proteinG: Value(3.5),
          carbsG: Value(22.0),
          fatG: Value(1.5),
          fiberG: Value(3.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('steamed_white_rice'),
          name: Value('Steamed White Rice (Cooked)'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(1.0),
          servingUnit: Value('cup (158g)'),
          calories: Value(205.0),
          proteinG: Value(4.2),
          carbsG: Value(45.0),
          fatG: Value(0.4),
          fiberG: Value(0.6),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('puliyodharai_rice'),
          name: Value('Puliyodharai (Tamarind Rice)'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(1.0),
          servingUnit: Value('cup (~180g)'),
          calories: Value(230.0),
          proteinG: Value(4.0),
          carbsG: Value(40.0),
          fatG: Value(6.0),
          fiberG: Value(2.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('lemon_rice'),
          name: Value('Elumichai Sadam (Lemon Rice)'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(1.0),
          servingUnit: Value('cup (~180g)'),
          calories: Value(240.0),
          proteinG: Value(5.0),
          carbsG: Value(38.0),
          fatG: Value(7.0),
          fiberG: Value(2.2),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('coconut_rice'),
          name: Value('Thengai Sadam (Coconut Rice)'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(1.0),
          servingUnit: Value('cup (~180g)'),
          calories: Value(250.0),
          proteinG: Value(4.0),
          carbsG: Value(40.0),
          fatG: Value(8.0),
          fiberG: Value(2.5),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('banana_fresh'),
          name: Value('Fresh Banana (Medium)'),
          brand: Value(null),
          category: Value('fruit'),
          servingSize: Value(1.0),
          servingUnit: Value('banana (118g)'),
          calories: Value(105.0),
          proteinG: Value(1.3),
          carbsG: Value(27.0),
          fatG: Value(0.3),
          fiberG: Value(3.1),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),

        // Vegetables & Poriyals
        const FoodItemsCompanion(
          id: Value('carrot_beans_poriyal'),
          name: Value('Carrot-Beans Poriyal'),
          brand: Value(null),
          category: Value('vegetable'),
          servingSize: Value(0.5),
          servingUnit: Value('cup (~100g)'),
          calories: Value(70.0),
          proteinG: Value(2.0),
          carbsG: Value(9.0),
          fatG: Value(3.0),
          fiberG: Value(3.2),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('cabbage_poriyal'),
          name: Value('Cabbage Poriyal'),
          brand: Value(null),
          category: Value('vegetable'),
          servingSize: Value(0.5),
          servingUnit: Value('cup (~100g)'),
          calories: Value(60.0),
          proteinG: Value(1.8),
          carbsG: Value(7.0),
          fatG: Value(2.8),
          fiberG: Value(2.8),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('beetroot_poriyal'),
          name: Value('Beetroot Poriyal'),
          brand: Value(null),
          category: Value('vegetable'),
          servingSize: Value(0.5),
          servingUnit: Value('cup (~100g)'),
          calories: Value(75.0),
          proteinG: Value(2.0),
          carbsG: Value(11.0),
          fatG: Value(2.5),
          fiberG: Value(2.5),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('sambar_drumstick'),
          name: Value('Tamil Sambar'),
          brand: Value(null),
          category: Value('dal'),
          servingSize: Value(1.0),
          servingUnit: Value('cup (~200g)'),
          calories: Value(130.0),
          proteinG: Value(5.5),
          carbsG: Value(18.0),
          fatG: Value(4.0),
          fiberG: Value(4.5),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('curd_dahi'),
          name: Value('Plain Curd / Yogurt'),
          brand: Value(null),
          category: Value('dairy'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(65.0),
          proteinG: Value(3.5),
          carbsG: Value(4.5),
          fatG: Value(3.5),
          fiberG: Value(0.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('roasted_peanuts'),
          name: Value('Roasted Peanuts / Groundnuts'),
          brand: Value(null),
          category: Value('snack'),
          servingSize: Value(25.0),
          servingUnit: Value('g (handful)'),
          calories: Value(145.0),
          proteinG: Value(6.5),
          carbsG: Value(4.0),
          fatG: Value(12.5),
          fiberG: Value(2.0),
          source: Value('icmr_nin'),
          isGeneric: Value(true),
        ),
      ]);
    }

    // 3. Seed Activities with MET values
    final existingActivities = await db.searchActivities('');
    if (existingActivities.isEmpty) {
      await db.insertActivitiesBatch([
        const ActivitiesCompanion(
          id: Value('act_bench_press'),
          name: Value('Barbell Bench Press (Chest & Triceps)'),
          category: Value('strength'),
          metValue: Value(5.0),
          defaultDurationMin: Value(45),
          description: Value('Compound horizontal push. 90s rest.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_overhead_press'),
          name: Value('Overhead Press / Military Press'),
          category: Value('strength'),
          metValue: Value(4.8),
          defaultDurationMin: Value(30),
          description: Value('Vertical pressing for delts and upper chest.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_barbell_squat'),
          name: Value('Barbell Back Squat'),
          category: Value('strength'),
          metValue: Value(6.0),
          defaultDurationMin: Value(45),
          description: Value('Heavy leg compound. 120s rest between sets.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_romanian_deadlift'),
          name: Value('Romanian Deadlift (RDL)'),
          category: Value('strength'),
          metValue: Value(5.5),
          defaultDurationMin: Value(30),
          description: Value('Hamstrings & glutes hip hinge.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_pull_ups'),
          name: Value('Pull-ups (Strict Bodyweight)'),
          category: Value('strength'),
          metValue: Value(7.5),
          defaultDurationMin: Value(20),
          description: Value('Bodyweight vertical pull for lats & biceps.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_barbell_rows'),
          name: Value('Barbell Bent-Over Rows'),
          category: Value('strength'),
          metValue: Value(5.5),
          defaultDurationMin: Value(30),
          description: Value('Horizontal pulling for mid-back & rhomboids.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_elliptical_hiit'),
          name: Value('HIIT Elliptical (Sprint Intervals)'),
          category: Value('hiit'),
          metValue: Value(10.0),
          defaultDurationMin: Value(15),
          description: Value('30s sprint (L5-7) / 30s recovery (L1-2) rounds.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_elliptical_zone2'),
          name: Value('Elliptical Steady State (Zone 2)'),
          category: Value('cardio'),
          metValue: Value(6.5),
          defaultDurationMin: Value(30),
          description: Value('Conversational pace cardio conditioning.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_walking'),
          name: Value('Brisk Walking (Outdoor)'),
          category: Value('cardio'),
          metValue: Value(3.8),
          defaultDurationMin: Value(30),
          description: Value('Active recovery and NEAT boost.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_plank_core'),
          name: Value('Core Conditioning (Plank & Leg Raises)'),
          category: Value('strength'),
          metValue: Value(4.0),
          defaultDurationMin: Value(15),
          description: Value('Isometric core holds and hanging leg raises.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_badminton'),
          name: Value('Badminton (Recreational / Match)'),
          category: Value('sports'),
          metValue: Value(6.0),
          defaultDurationMin: Value(45),
          description: Value('High agility sport.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_yoga'),
          name: Value('Yoga & Mobility Flow'),
          category: Value('flexibility'),
          metValue: Value(3.0),
          defaultDurationMin: Value(30),
          description: Value('Active recovery and joint decompression.'),
        ),
      ]);
    }

    // 4. Seed Recipes from refeerece.html
    final existingRecipes = await db.getAllRecipes();
    if (existingRecipes.isEmpty) {
      await db.insertRecipesBatch([
        RecipesCompanion.insert(
          id: 'vengaya_muttai_poriyal',
          name: 'Vengaya Muttai Poriyal (4 eggs + 4 chapatis)',
          tamilName: const Value('வெங்காய முட்டை பொரியல்'),
          mealSlot: 'breakfast',
          dayOfWeek: const Value('Mon'),
          calories: 700.0,
          proteinG: 37.0,
          carbsG: 74.0,
          fatG: 21.0,
          fiberG: const Value(8.0),
          ingredientsJson: jsonEncode([
            '4 whole eggs',
            '4 whole wheat chapatis',
            '1 small onion (finely chopped)',
            '1 green chili (slit)',
            '1/4 tsp turmeric',
            'A few curry leaves',
            '1 tsp cooking oil',
            'Salt to taste'
          ]),
          method: 'Heat 1 tsp oil, splutter curry leaves, sauté onion and chili 2–3 min till soft. Add turmeric and salt, crack in 4 eggs, scramble on medium heat 2–3 min until just set. Serve with 4 hot chapatis.',
          shelfLifeTip: const Value('Eaten fresh at breakfast (6:30 AM).'),
          tags: const Value('breakfast,high-protein,eggs'),
        ),
        RecipesCompanion.insert(
          id: 'milagu_omelette',
          name: 'Milagu Omelette (4 eggs + 4 chapatis)',
          tamilName: const Value('மிளகு ஆம்லெட்'),
          mealSlot: 'breakfast',
          dayOfWeek: const Value('Tue'),
          calories: 700.0,
          proteinG: 37.0,
          carbsG: 74.0,
          fatG: 21.0,
          fiberG: const Value(8.0),
          ingredientsJson: jsonEncode([
            '4 whole eggs',
            '4 whole wheat chapatis',
            '1/2 tsp crushed black pepper',
            '2 tbsp chopped coriander',
            '1 small onion (finely chopped)',
            '1 tsp cooking oil',
            'Salt'
          ]),
          method: 'Whisk eggs with crushed black pepper, onion, coriander, and salt. Cook flat-omelette style in pan with 1 tsp oil, ~2 min per side. Pair with 4 chapatis.',
          shelfLifeTip: const Value('Fresh breakfast.'),
          tags: const Value('breakfast,eggs,pepper'),
        ),
        RecipesCompanion.insert(
          id: 'boiled_eggs_kachumber',
          name: 'Boiled Eggs + Tomato-Onion Kachumber',
          tamilName: const Value('முட்டை கச்சும்பர்'),
          mealSlot: 'breakfast',
          dayOfWeek: const Value('Wed'),
          calories: 680.0,
          proteinG: 36.0,
          carbsG: 74.0,
          fatG: 20.0,
          fiberG: const Value(9.0),
          ingredientsJson: jsonEncode([
            '4 whole boiled eggs',
            '4 whole wheat chapatis',
            '1 tomato (finely chopped)',
            '1 onion (finely chopped)',
            'Squeeze of fresh lemon',
            'Salt and black pepper'
          ]),
          method: 'Boil eggs 8–9 min, peel and halve. Toss tomato and onion with lemon juice, salt, and pepper. Fast grab-and-go option.',
          shelfLifeTip: const Value('Fastest option for rushed mornings.'),
          tags: const Value('breakfast,quick,boiled-eggs'),
        ),
        RecipesCompanion.insert(
          id: 'naatu_kozhi_milagu_varuval',
          name: 'Naatu Kozhi Milagu Varuval (Lunch Box)',
          tamilName: const Value('நாட்டுக்கோழி மிளகு வறுவல்'),
          mealSlot: 'lunch',
          dayOfWeek: const Value('Mon'),
          calories: 530.0,
          proteinG: 44.0,
          carbsG: 51.0,
          fatG: 16.0,
          fiberG: const Value(5.0),
          ingredientsJson: jsonEncode([
            '180g boneless chicken (cubed)',
            '1 cup cooked rice (Puliyodharai / Plain)',
            '1/2 cup carrot-beans poriyal',
            '1 tsp crushed pepper',
            '1/2 tsp turmeric',
            '1 tsp ginger-garlic paste',
            'Curry leaves',
            '1 tsp oil',
            'Salt'
          ]),
          method: 'Marinate chicken with turmeric, salt, and ginger-garlic. Air-fry at 200°C for 12–15 min or pan-roast in 1 tsp oil on medium-high for 8–10 min until dry and browned. Toss with crushed pepper and curry leaves.',
          shelfLifeTip: const Value('Cool completely before packing — dry preparation safe for 6 hrs unrefrigerated.'),
          tags: const Value('lunch,dry-pack,chicken,mon'),
        ),
        RecipesCompanion.insert(
          id: 'soya_chunks_varuval',
          name: 'Soya Chunks Milagu Varuval (Lunch Box)',
          tamilName: const Value('சோயா சங்ஸ் வறுவல்'),
          mealSlot: 'lunch',
          dayOfWeek: const Value('Tue'),
          calories: 480.0,
          proteinG: 32.0,
          carbsG: 65.0,
          fatG: 14.0,
          fiberG: const Value(10.0),
          ingredientsJson: jsonEncode([
            '50g dry soya chunks',
            '1 cup lemon rice (Elumichai sadam)',
            '1/2 cup cabbage poriyal',
            '1 onion',
            '1/2 tsp pepper & turmeric',
            'Curry leaves',
            '1 tsp oil'
          ]),
          method: 'Rehydrate soya in hot water 10 min, then squeeze out water firmly. Sauté onion in 1 tsp oil, add soya chunks and spices, dry-roast 6–8 min until edges crisp.',
          shelfLifeTip: const Value('Squeeze water thoroughly for long shelf-life in bag.'),
          tags: const Value('lunch,dry-pack,soya,tue'),
        ),
        RecipesCompanion.insert(
          id: 'vella_kadalai_sundal',
          name: 'Vella Kadalai Sundal (Lunch Box)',
          tamilName: const Value('வெள்ளை கடலை சுண்டல்'),
          mealSlot: 'lunch',
          dayOfWeek: const Value('Wed'),
          calories: 510.0,
          proteinG: 21.0,
          carbsG: 82.0,
          fatG: 15.0,
          fiberG: const Value(12.0),
          ingredientsJson: jsonEncode([
            '60g dry white chickpeas (soaked & boiled)',
            '1 cup tamarind rice (Puliyodharai)',
            '1 boiled egg (optional side)',
            'Mustard seeds, 1 dry red chili, curry leaves',
            '2 tbsp grated coconut',
            '1 tsp oil',
            'Salt'
          ]),
          method: 'Temper mustard seeds, red chili, and curry leaves in 1 tsp oil. Add boiled chickpeas, toss with coconut and salt, cook 2–3 min till completely dry.',
          shelfLifeTip: const Value('Classic temple travel food — naturally preserves for 6+ hours.'),
          tags: const Value('lunch,dry-pack,sundal,wed'),
        ),
        RecipesCompanion.insert(
          id: 'paneer_chettinad_varuval',
          name: 'Paneer Chettinad Varuval (Lunch Box)',
          tamilName: const Value('பன்னீர் செட்டிநாடு வறுவல்'),
          mealSlot: 'lunch',
          dayOfWeek: const Value('Thu'),
          calories: 580.0,
          proteinG: 24.0,
          carbsG: 59.0,
          fatG: 29.0,
          fiberG: const Value(6.0),
          ingredientsJson: jsonEncode([
            '100g paneer cubes',
            '1 cup cooked rice',
            '1/2 cup poriyal',
            '1 onion, 1 tomato',
            '1/2 tsp Chettinad masala',
            'Curry leaves',
            '1 tsp oil'
          ]),
          method: 'Sear paneer cubes in dry pan or air-fry 5 min till firm. Separately cook onion, tomato, and spices into thick dry masala, then toss paneer through.',
          shelfLifeTip: const Value('Keep dry-fried, no watery gravy so it holds clean in lunch box.'),
          tags: const Value('lunch,dry-pack,paneer,thu'),
        ),
        RecipesCompanion.insert(
          id: 'kozhi_chukka_lunch',
          name: 'Kozhi Chukka with Coconut Bits (Lunch Box)',
          tamilName: const Value('கோழி சுக்கா'),
          mealSlot: 'lunch',
          dayOfWeek: const Value('Fri'),
          calories: 550.0,
          proteinG: 44.0,
          carbsG: 54.0,
          fatG: 18.0,
          fiberG: const Value(5.5),
          ingredientsJson: jsonEncode([
            '180g chicken',
            '1 cup coconut rice or plain rice',
            '1/2 cup beetroot poriyal',
            '1 onion, curry leaves',
            '2 tbsp fresh grated coconut',
            '1/2 tsp chili & turmeric powder',
            '1 tsp oil'
          ]),
          method: 'Pan-roast marinated chicken in 1 tsp oil. In final 2 min, toss through sautéed onions, fresh coconut bits, and curry leaves for dry aromatic finish.',
          shelfLifeTip: const Value('Cool fully before sealing lunchbox.'),
          tags: const Value('lunch,dry-pack,chicken,fri'),
        ),
        RecipesCompanion.insert(
          id: 'naatu_kozhi_kuzhambu_dinner',
          name: 'Naatu Kozhi Kuzhambu (Dinner — 220g Chicken + 3 Chapatis)',
          tamilName: const Value('நாட்டுக்கோழி குழம்பு'),
          mealSlot: 'dinner',
          dayOfWeek: const Value('Mon / Thu'),
          calories: 820.0,
          proteinG: 55.0,
          carbsG: 72.0,
          fatG: 22.0,
          fiberG: const Value(9.0),
          ingredientsJson: jsonEncode([
            '220g country chicken',
            '3 whole wheat chapatis',
            '1 onion, 2 tomatoes',
            '3 tbsp grated coconut (ground to paste)',
            '1 tsp ginger-garlic paste',
            'Turmeric, chili, coriander powder',
            'Curry leaves',
            '1 tsp oil'
          ]),
          method: 'Sauté onion and ginger-garlic, add tomatoes and spice powders. Sear chicken 3–4 min, add coconut paste and water, simmer covered 15–20 min till tender. Eaten fresh with hot chapatis.',
          shelfLifeTip: const Value('Eaten fresh at home — gravy is perfect.'),
          tags: const Value('dinner,high-protein,chicken,curry'),
        ),
        RecipesCompanion.insert(
          id: 'milagu_kozhi_varuval_dinner',
          name: 'Milagu Kozhi Varuval (Dinner — 220g Chicken + 3 Chapatis)',
          tamilName: const Value('மிளகு கோழி வறுவல்'),
          mealSlot: 'dinner',
          dayOfWeek: const Value('Tue / Fri'),
          calories: 800.0,
          proteinG: 56.0,
          carbsG: 70.0,
          fatG: 20.0,
          fiberG: const Value(9.0),
          ingredientsJson: jsonEncode([
            '220g boneless chicken',
            '3 whole wheat chapatis',
            '1.5 tsp freshly crushed black pepper',
            '1 tsp ginger-garlic paste',
            'Curry leaves',
            '1 tsp oil',
            'Salt'
          ]),
          method: 'Marinate chicken 15 min, air-fry at 200°C for 15–18 min or pan-roast in 1 tsp oil until dry and browned. Toss with crushed pepper and curry leaves.',
          shelfLifeTip: const Value('Fresh post-workout dinner.'),
          tags: const Value('dinner,pepper,chicken,high-protein'),
        ),
      ]);
    }
  }
}
