import 'dart:convert';
import 'package:drift/drift.dart';
import 'app_database.dart';
import 'recipe_seed_list.dart';

class SeedData {
  static Future<void> seedInitialData(AppDatabase db) async {
    // 1. Seed Default User with Recomp Manual v3 Macro Targets (2,350 kcal)
    final existingUser = await db.getUserProfile();
    if (existingUser == null) {
      await db.saveUserProfile(
        UsersCompanion.insert(
          id: const Value('default_user'),
          heightCm: const Value(160.0),
          weightKg: const Value(62.0),
          age: const Value(21),
          activityLevel: const Value('moderate'),
          calorieTarget: const Value(2350),
          proteinTargetG: const Value(155.0),
          carbTargetG: const Value(260.0),
          fatTargetG: const Value(70.0),
          fiberTargetG: const Value(35.0),
          waterTargetMl: const Value(3000),
          stepsTarget: const Value(10000),
        ),
      );
    }

    // 2. Seed Food Items from USDA FoodData Central 2024–25 & Tamil Nadu manual
    final existingFoods = await db.searchFoodItems('');
    if (existingFoods.isEmpty) {
      await db.insertFoodItemsBatch([
        // Proteins
        const FoodItemsCompanion(
          id: Value('whole_egg_raw'),
          name: Value('Whole Egg (Large, ~55g)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(1.0),
          servingUnit: Value('egg (~55g)'),
          calories: Value(85.0),
          proteinG: Value(7.2),
          carbsG: Value(0.6),
          fatG: Value(6.0),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('egg_white_raw'),
          name: Value('Egg White (~30g)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(1.0),
          servingUnit: Value('white (~30g)'),
          calories: Value(16.0),
          proteinG: Value(3.3),
          carbsG: Value(0.2),
          fatG: Value(0.1),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('boiler_chicken_breast_cooked'),
          name: Value('Boiler Chicken Breast (Cooked, No Skin)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(165.0),
          proteinG: Value(31.0),
          carbsG: Value(0.0),
          fatG: Value(3.6),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('chicken_breast_boneless_raw'),
          name: Value('Chicken Breast (Boneless, Raw)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(120.0),
          proteinG: Value(23.5),
          carbsG: Value(0.0),
          fatG: Value(2.6),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('soya_chunks_dry'),
          name: Value('Soya Chunks (Dry)'),
          brand: Value(null),
          category: Value('protein'),
          servingSize: Value(50.0),
          servingUnit: Value('g'),
          calories: Value(172.5),
          proteinG: Value(26.0),
          carbsG: Value(16.5),
          fatG: Value(0.25),
          fiberG: Value(7.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('white_chickpeas_cooked'),
          name: Value('White Chickpeas (Vella Kadalai, Cooked)'),
          brand: Value(null),
          category: Value('legume'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(164.0),
          proteinG: Value(8.9),
          carbsG: Value(27.0),
          fatG: Value(2.6),
          fiberG: Value(7.6),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('kidney_beans_rajma_cooked'),
          name: Value('Kidney Beans (Rajma, Cooked)'),
          brand: Value(null),
          category: Value('legume'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(127.0),
          proteinG: Value(8.7),
          carbsG: Value(23.0),
          fatG: Value(0.5),
          fiberG: Value(7.4),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('green_moong_cooked'),
          name: Value('Whole Green Moong (Pachai Payaru, Cooked)'),
          brand: Value(null),
          category: Value('legume'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(105.0),
          proteinG: Value(7.0),
          carbsG: Value(19.0),
          fatG: Value(0.4),
          fiberG: Value(7.6),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('paneer_fresh'),
          name: Value('Paneer (Full-Fat Cottage Cheese)'),
          brand: Value(null),
          category: Value('dairy'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(265.0),
          proteinG: Value(18.0),
          carbsG: Value(3.4),
          fatG: Value(20.0),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('whey_protein_isolate'),
          name: Value('Whey Protein Isolate (1 Scoop)'),
          brand: Value('Generic'),
          category: Value('supplement'),
          servingSize: Value(1.0),
          servingUnit: Value('scoop (30g)'),
          calories: Value(114.0),
          proteinG: Value(27.0),
          carbsG: Value(1.2),
          fatG: Value(0.3),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('curd_whole_milk'),
          name: Value('Curd / Dahi (Indian, Whole Milk)'),
          brand: Value(null),
          category: Value('dairy'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(65.0),
          proteinG: Value(3.5),
          carbsG: Value(4.7),
          fatG: Value(3.3),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('hung_curd_strained'),
          name: Value('Hung Curd / Strained Greek Style'),
          brand: Value(null),
          category: Value('dairy'),
          servingSize: Value(100.0),
          servingUnit: Value('g'),
          calories: Value(98.0),
          proteinG: Value(11.0),
          carbsG: Value(3.4),
          fatG: Value(4.3),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),

        // Carbs & Grains
        const FoodItemsCompanion(
          id: Value('wheat_chapati_medium'),
          name: Value('Chapati / Roti (Medium, 40g, No Oil)'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(1.0),
          servingUnit: Value('chapati (40g)'),
          calories: Value(112.0),
          proteinG: Value(3.2),
          carbsG: Value(21.0),
          fatG: Value(0.5),
          fiberG: Value(2.4),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('white_rice_cooked'),
          name: Value('White Rice (Cooked)'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(1.0),
          servingUnit: Value('cup (200g)'),
          calories: Value(260.0),
          proteinG: Value(5.4),
          carbsG: Value(56.0),
          fatG: Value(0.6),
          fiberG: Value(0.8),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('rolled_oats_dry'),
          name: Value('Rolled Oats (Dry)'),
          brand: Value(null),
          category: Value('grain'),
          servingSize: Value(40.0),
          servingUnit: Value('g serving'),
          calories: Value(156.0),
          proteinG: Value(5.2),
          carbsG: Value(26.8),
          fatG: Value(2.8),
          fiberG: Value(4.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('banana_medium'),
          name: Value('Banana (Medium, ~120g)'),
          brand: Value(null),
          category: Value('fruit'),
          servingSize: Value(1.0),
          servingUnit: Value('banana (120g)'),
          calories: Value(107.0),
          proteinG: Value(1.3),
          carbsG: Value(27.6),
          fatG: Value(0.4),
          fiberG: Value(3.1),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('roasted_peanuts_serving'),
          name: Value('Peanuts (Roasted, Unsalted)'),
          brand: Value(null),
          category: Value('snack'),
          servingSize: Value(25.0),
          servingUnit: Value('g (handful)'),
          calories: Value(142.0),
          proteinG: Value(6.5),
          carbsG: Value(4.0),
          fatG: Value(12.2),
          fiberG: Value(2.1),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('cooking_oil_tsp'),
          name: Value('Cooking Oil (1 tsp / 4g)'),
          brand: Value(null),
          category: Value('fat'),
          servingSize: Value(1.0),
          servingUnit: Value('tsp (4g)'),
          calories: Value(35.0),
          proteinG: Value(0.0),
          carbsG: Value(0.0),
          fatG: Value(4.0),
          fiberG: Value(0.0),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
        const FoodItemsCompanion(
          id: Value('fresh_coconut_grated'),
          name: Value('Fresh Grated Coconut (2 tbsp / 15g)'),
          brand: Value(null),
          category: Value('fat'),
          servingSize: Value(15.0),
          servingUnit: Value('g (2 tbsp)'),
          calories: Value(53.0),
          proteinG: Value(0.5),
          carbsG: Value(2.2),
          fatG: Value(5.0),
          fiberG: Value(1.4),
          source: Value('usda_fdc'),
          isGeneric: Value(true),
        ),
      ]);
    }

    // 3. Seed Activities with MET values from Recomp Manual v3
    final existingActivities = await db.searchActivities('');
    if (existingActivities.isEmpty) {
      await db.insertActivitiesBatch([
        const ActivitiesCompanion(
          id: Value('act_upper_a_push'),
          name: Value('Upper A: Push Focus (Bench, Incline DB, OHP, Skulls)'),
          category: Value('strength'),
          metValue: Value(5.5),
          defaultDurationMin: Value(55),
          description: Value('Compound push emphasis. 90-120s rest on heavy compounds.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_lower_a_squat'),
          name: Value('Lower A: Quad Focus (Squat, RDL, Walking Lunge, Core)'),
          category: Value('strength'),
          metValue: Value(6.0),
          defaultDurationMin: Value(55),
          description: Value('Squat pattern emphasis. Knees over toes, controlled lowering.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_zone_2_elliptical'),
          name: Value('Zone 2 Conditioning (Elliptical Steady State)'),
          category: Value('cardio'),
          metValue: Value(6.5),
          defaultDurationMin: Value(30),
          description: Value('Continuous conversational pace, 120-140 bpm. Active recovery.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_upper_b_pull'),
          name: Value('Upper B: Pull Focus (Pull-ups, Rows, Curls, Incline Press)'),
          category: Value('strength'),
          metValue: Value(5.5),
          defaultDurationMin: Value(55),
          description: Value('Back and biceps frequency. Dead hang pull-ups + accessory.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_lower_b_hiit'),
          name: Value('Lower B: Hinge + HIIT (Goblet Squat, Sumo DB, Sprint Rounds)'),
          category: Value('hiit'),
          metValue: Value(8.0),
          defaultDurationMin: Value(50),
          description: Value('Hinge strength + 6-8 rounds 30s sprint/30s recovery on elliptical.'),
        ),
        const ActivitiesCompanion(
          id: Value('act_recovery_walk'),
          name: Value('Active Recovery Walk (Saturday Walk + Grocery)'),
          category: Value('cardio'),
          metValue: Value(3.5),
          defaultDurationMin: Value(30),
          description: Value('20-30 min easy walking for NEAT and weekly fresh grocery run.'),
        ),
      ]);
    }

    // 4. Seed All 90 Recomp Recipes from Recomp_Manual_v3.html
    await db.insertRecipesBatch(recompRecipesV3);
  }
}
