"""Export the canonical synonym table to Dart so the app canonicalizes offline.

app/data/ingredient_synonyms.py stays the single source of truth; the Dart
file is generated and tests/test_dart_synonyms_in_sync.py fails if it drifts.

Usage:
    python -m app.scripts.export_synonyms_dart
"""
from __future__ import annotations

import json
from pathlib import Path

from app.data.ingredient_synonyms import INGREDIENT_SYNONYMS

DART_PATH = Path(__file__).resolve().parents[2] / "lib" / "core" / "ingredients" / "ingredient_synonyms.g.dart"


def render() -> str:
    lines = [
        "// GENERATED by `python -m app.scripts.export_synonyms_dart` — do not edit.",
        "// Source of truth: app/data/ingredient_synonyms.py",
        "",
        "const Map<String, String> ingredientSynonyms = {",
    ]
    for key in sorted(INGREDIENT_SYNONYMS):
        lines.append(f"  {json.dumps(key)}: {json.dumps(INGREDIENT_SYNONYMS[key])},")
    lines.append("};")
    return "\n".join(lines).replace("$", "\\$") + "\n"


if __name__ == "__main__":
    DART_PATH.parent.mkdir(parents=True, exist_ok=True)
    DART_PATH.write_text(render(), encoding="utf-8")
    print(f"Wrote {len(INGREDIENT_SYNONYMS)} synonyms to {DART_PATH}")
